function [HitRate_IT, FARate_IT, HitRate_IT_avg, FARate_IT_avg,...
          HitRate_IB, FARate_IB, HitRate_IB_avg, FARate_IB_avg,...
          HitRate_CT, FARate_CT, HitRate_CT_avg, FARate_CT_avg,...
          HitRate_CB, FARate_CB, HitRate_CB_avg, FARate_CB_avg] =...
          congruencyrates(rates, nTrials, nSubsets)
%CONGRUENCYRATES computes hit and false alarm rates for
%   the four congruency cases

    % Incongruent Top
    HitRate_IT =...
        adjustrates4sdt(reshape(rates(1,1,:,:), nSubsets, []),...
                        nTrials);
    HitRate_IT = mean(HitRate_IT, 2);
    HitRate_IT_avg = mean(HitRate_IT);

    FARate_IT =...
        adjustrates4sdt(reshape(rates(1,2,:,:), nSubsets, []),...
                        nTrials);
    FARate_IT = mean(FARate_IT, 2);
    FARate_IT_avg = mean(FARate_IT);

    % Incongruent Bottom
    HitRate_IB =...
        adjustrates4sdt(reshape(rates(2,1,:,:), nSubsets, []),...
                        nTrials);
    HitRate_IB = mean(HitRate_IB, 2);
    HitRate_IB_avg = mean(HitRate_IB);
    
    FARate_IB =...
        adjustrates4sdt(reshape(rates(2,2,:,:), nSubsets, []),...
                        nTrials);
    FARate_IB = mean(FARate_IB, 2);
    FARate_IB_avg = mean(FARate_IB);
    
    % Congruent Top
    HitRate_CT =...
        adjustrates4sdt(reshape(rates(3,1,:,:), nSubsets, []),...
                        nTrials);
    HitRate_CT = mean(HitRate_CT, 2);
    HitRate_CT_avg = mean(HitRate_CT);
    
    FARate_CT =...
        adjustrates4sdt(reshape(rates(3,2,:,:), nSubsets, []),...
                        nTrials);
    FARate_CT = mean(FARate_CT, 2);
    FARate_CT_avg = mean(FARate_CT);

    % Congruent Bottom
    HitRate_CB =...
        adjustrates4sdt(reshape(rates(4,1,:,:), nSubsets, []),...
                        nTrials);
    HitRate_CB = mean(HitRate_CB, 2);
    HitRate_CB_avg = mean(HitRate_CB);
    
    FARate_CB =...
        adjustrates4sdt(reshape(rates(4,2,:,:), nSubsets, []),...
                        nTrials);
    FARate_CB = mean(FARate_CB, 2);
    FARate_CB_avg = mean(FARate_CB);
end