%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PERCENT ACCURACY ON INDIVIDUAL EXPRESSIONS DURING TESTING %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Noncomposite face images
% left-shifted
Pct_Acc.NC_LS_A_Expr =...
    100*diag(Conf_Mx.NC_LS_A)./sum(Conf_Mx.NC_LS_A, 2);
% right-shifted
Pct_Acc.NC_RS_A_Expr =...
    100*diag(Conf_Mx.NC_RS_A)./sum(Conf_Mx.NC_RS_A, 2);
% all
Pct_Acc.NC_A_Expr =...
    100*diag(Conf_Mx.NC_A)./sum(Conf_Mx.NC_A, 2);

% Top half face images
% left-shifted
Pct_Acc.TH_LS_A_Expr =...
    100*diag(Conf_Mx.TH_LS_A)./sum(Conf_Mx.TH_LS_A, 2);
% right-shifted
Pct_Acc.TH_RS_A_Expr =...
    100*diag(Conf_Mx.TH_RS_A)./sum(Conf_Mx.TH_RS_A, 2);
% all
Pct_Acc.TH_A_Expr =...
    100*diag(Conf_Mx.TH_A)./sum(Conf_Mx.TH_A, 2);

% Bottom half face images
% left-shifted
Pct_Acc.BH_LS_A_Expr =...
    100*diag(Conf_Mx.BH_LS_A)./sum(Conf_Mx.BH_LS_A, 2);
% right-shifted
Pct_Acc.BH_RS_A_Expr =...
    100*diag(Conf_Mx.BH_RS_A)./sum(Conf_Mx.BH_RS_A, 2);
% all
Pct_Acc.BH_A_Expr =...
    100*diag(Conf_Mx.BH_A)./sum(Conf_Mx.BH_A, 2);


%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OVERALL PERCENT ACCURACY DURING TESTING (AND CONFIDENCE INTERVALS) %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Noncomposite face images
% left-shifted
Pct_Acc.NC_LS_A_all = mean(mean(Pct_Acc.NC_LS_A));
% right-shifted
Pct_Acc.NC_RS_A_all = mean(mean(Pct_Acc.NC_RS_A));
% all
Pct_Acc.NC_A_all = mean(mean(Pct_Acc.NC_A));

% left-shifted
Conf_Int.Pct_Acc.NC_LS_A_all =...
    confidenceinterval(mean(Pct_Acc.NC_LS_A, 2));
% right-shifted
Conf_Int.Pct_Acc.NC_RS_A_all =...
    confidenceinterval(mean(Pct_Acc.NC_RS_A, 2));
% all
Conf_Int.Pct_Acc.NC_A_all =...
    confidenceinterval(mean(Pct_Acc.NC_A, 2));


% Top half face images
% left-shifted
Pct_Acc.TH_LS_A_all = mean(mean(Pct_Acc.TH_LS_A));
% right-shifted
Pct_Acc.TH_RS_A_all = mean(mean(Pct_Acc.TH_RS_A));
% all
Pct_Acc.TH_A_all = mean(mean(Pct_Acc.TH_A));

% left-shifted
Conf_Int.Pct_Acc.TH_LS_A_all =...
    confidenceinterval(mean(Pct_Acc.TH_LS_A, 2));
% right-shifted
Conf_Int.Pct_Acc.TH_RS_A_all =...
    confidenceinterval(mean(Pct_Acc.TH_RS_A, 2));
% all
Conf_Int.Pct_Acc.TH_A_all =...
    confidenceinterval(mean(Pct_Acc.TH_A, 2));


% Bottom half face images
% left-shifted
Pct_Acc.BH_LS_A_all = mean(mean(Pct_Acc.BH_LS_A));
% right-shifted
Pct_Acc.BH_RS_A_all = mean(mean(Pct_Acc.BH_RS_A));
% all
Pct_Acc.BH_A_all = mean(mean(Pct_Acc.BH_A));

% left-shifted
Conf_Int.Pct_Acc.BH_LS_A_all =...
    confidenceinterval(mean(Pct_Acc.BH_LS_A, 2));
% right-shifted
Conf_Int.Pct_Acc.BH_RS_A_all =...
    confidenceinterval(mean(Pct_Acc.BH_RS_A, 2));
% all
Conf_Int.Pct_Acc.BH_A_all =...
    confidenceinterval(mean(Pct_Acc.BH_A, 2));

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 1: COMPLETE COMPOSITE PARADIGM %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Signal Detection Theory
% Overall
%
% Rates of 0 and 1 need to be adjusted for the computations
% left-shifted aligned
[HitRate.All.IT_LS_A, FARate.All.IT_LS_A,...
    HitRate.IT_LS_A_all, FARate.IT_LS_A_all,...
 HitRate.All.IB_LS_A, FARate.All.IB_LS_A,...
    HitRate.IB_LS_A_all, FARate.IB_LS_A_all,...
 HitRate.All.CT_LS_A, FARate.All.CT_LS_A,...
    HitRate.CT_LS_A_all, FARate.CT_LS_A_all,...
 HitRate.All.CB_LS_A, FARate.All.CB_LS_A,...
    HitRate.CB_LS_A_all, FARate.CB_LS_A_all] =...
congruencyrates(RatesS.All.LS_A,...
                n.TrialsS.All,...
                n.Subsets);
%
% right-shifted aligned
[HitRate.All.IT_RS_A, FARate.All.IT_RS_A,...
    HitRate.IT_RS_A_all, FARate.IT_RS_A_all,...
 HitRate.All.IB_RS_A, FARate.All.IB_RS_A,...
    HitRate.IB_RS_A_all, FARate.IB_RS_A_all,...
 HitRate.All.CT_RS_A, FARate.All.CT_RS_A,...
    HitRate.CT_RS_A_all, FARate.CT_RS_A_all,...
 HitRate.All.CB_RS_A, FARate.All.CB_RS_A,...
    HitRate.CB_RS_A_all, FARate.CB_RS_A_all] =...
congruencyrates(RatesS.All.RS_A,...
                n.TrialsS.All,...
                n.Subsets);
%
% top-left bottom-right misaligned
[HitRate.All.IT_TLBR_MA, FARate.All.IT_TLBR_MA,...
    HitRate.IT_TLBR_MA_all, FARate.IT_TLBR_MA_all,...
 HitRate.All.IB_TLBR_MA, FARate.All.IB_TLBR_MA,...
    HitRate.IB_TLBR_MA_all, FARate.IB_TLBR_MA_all,...
 HitRate.All.CT_TLBR_MA, FARate.All.CT_TLBR_MA,...
    HitRate.CT_TLBR_MA_all, FARate.CT_TLBR_MA_all,...
 HitRate.All.CB_TLBR_MA, FARate.All.CB_TLBR_MA,...
    HitRate.CB_TLBR_MA_all, FARate.CB_TLBR_MA_all] =...
congruencyrates(RatesS.All.TLBR_MA,...
                n.TrialsS.All,...
                n.Subsets);
%
% top-right bottom-left misaligned
[HitRate.All.IT_TRBL_MA, FARate.All.IT_TRBL_MA,...
    HitRate.IT_TRBL_MA_all, FARate.IT_TRBL_MA_all,...
 HitRate.All.IB_TRBL_MA, FARate.All.IB_TRBL_MA,...
    HitRate.IB_TRBL_MA_all, FARate.IB_TRBL_MA_all,...
 HitRate.All.CT_TRBL_MA, FARate.All.CT_TRBL_MA,...
    HitRate.CT_TRBL_MA_all, FARate.CT_TRBL_MA_all,...
 HitRate.All.CB_TRBL_MA, FARate.All.CB_TRBL_MA,...
    HitRate.CB_TRBL_MA_all, FARate.CB_TRBL_MA_all] =...
congruencyrates(RatesS.All.TRBL_MA,...
                n.TrialsS.All,...
                n.Subsets);


% criterion C & d-prime
% Determine if the signal detection theory computations can be
% applied to the data
Exception.All = 0;
while(1)
    % left-shifted aligned
    %
    % Incongruent Top
    if isvalid4sdt(HitRate.All.IT_LS_A, FARate.All.IT_LS_A) == 1
        Exception.All = 1;
        Exception.Message = 'IT_LS_A';
        break;
    end
    SDT.All.dprime_IT_LS_A =...
        sensitivitycriterion4sdt(HitRate.All.IT_LS_A,...
                                 FARate.All.IT_LS_A);
    Conf_Int.All.dprime_IT_LS_A =...
        confidenceinterval(SDT.All.dprime_IT_LS_A);

    %
    % Incongruent Bottom
    if isvalid4sdt(HitRate.All.IB_LS_A, FARate.All.IB_LS_A) == 1
        Exception.All = 1;
        Exception.Message = 'IB_LS_A';
        break;
    end
    SDT.All.dprime_IB_LS_A =...
        sensitivitycriterion4sdt(HitRate.All.IB_LS_A,...
                                 FARate.All.IB_LS_A);
    Conf_Int.All.dprime_IB_LS_A =...
        confidenceinterval(SDT.All.dprime_IB_LS_A);

    %
    % Congruent Top
    if isvalid4sdt(HitRate.All.CT_LS_A, FARate.All.CT_LS_A) == 1
        Exception.All = 1;
        Exception.Message = 'CT_LS_A';
        break;
    end
    SDT.All.dprime_CT_LS_A =...
        sensitivitycriterion4sdt(HitRate.All.CT_LS_A,...
                                 FARate.All.CT_LS_A);
    Conf_Int.All.dprime_CT_LS_A =...
        confidenceinterval(SDT.All.dprime_CT_LS_A);

    %
    % Congruent Bottom
    if isvalid4sdt(HitRate.All.CB_LS_A, FARate.All.CB_LS_A) == 1
        Exception.All = 1;
        Exception.Message = 'CB_LS_A';
        break;
    end
    SDT.All.dprime_CB_LS_A =... 
        sensitivitycriterion4sdt(HitRate.All.CB_LS_A,...
                                 FARate.All.CB_LS_A);
    Conf_Int.All.dprime_CB_LS_A =...
        confidenceinterval(SDT.All.dprime_CB_LS_A);

    %
    % right-shifted aligned
    %
    % Incongruent Top
    if isvalid4sdt(HitRate.All.IT_RS_A, FARate.All.IT_RS_A) == 1
        Exception.All = 1;
        Exception.Message = 'IT_RS_A';
        break;
    end
    SDT.All.dprime_IT_RS_A =...
        sensitivitycriterion4sdt(HitRate.All.IT_RS_A,...
                                 FARate.All.IT_RS_A);
    Conf_Int.All.dprime_IT_RS_A =...
        confidenceinterval(SDT.All.dprime_IT_RS_A);

    %
    % Incongruent Bottom
    if isvalid4sdt(HitRate.All.IB_RS_A, FARate.All.IB_RS_A) == 1
        Exception.All = 1;
        Exception.Message = 'IB_RS_A';
        break;
    end
    SDT.All.dprime_IB_RS_A =...
        sensitivitycriterion4sdt(HitRate.All.IB_RS_A,...
                                 FARate.All.IB_RS_A);
    Conf_Int.All.dprime_IB_RS_A =...
        confidenceinterval(SDT.All.dprime_IB_RS_A);

    %
    % Congruent Top
    if isvalid4sdt(HitRate.All.CT_RS_A, FARate.All.CT_RS_A) == 1
        Exception.All = 1;
        Exception.Message = 'CT_RS_A';
        break;
    end
    SDT.All.dprime_CT_RS_A =...
        sensitivitycriterion4sdt(HitRate.All.CT_RS_A,...
                                 FARate.All.CT_RS_A);
    Conf_Int.All.dprime_CT_RS_A =...
        confidenceinterval(SDT.All.dprime_CT_RS_A);

    %
    % Congruent Bottom
    if isvalid4sdt(HitRate.All.CB_RS_A, FARate.All.CB_RS_A) == 1
        Exception.All = 1;
        Exception.Message = 'CB_RS_A';
        break;
    end
    SDT.All.dprime_CB_RS_A =...
        sensitivitycriterion4sdt(HitRate.All.CB_RS_A,...
                                 FARate.All.CB_RS_A);
    Conf_Int.All.dprime_CB_RS_A =...
        confidenceinterval(SDT.All.dprime_CB_RS_A);

    %
    % top-left bottom-right misaligned
    %
    % Incongruent Top
    if isvalid4sdt(HitRate.All.IT_TLBR_MA,...
                   FARate.All.IT_TLBR_MA) == 1
        Exception.All = 1;
        Exception.Message = 'IT_TLBR_MA';
        break;
    end
    SDT.All.dprime_IT_TLBR_MA =...
        sensitivitycriterion4sdt(HitRate.All.IT_TLBR_MA,...
                                 FARate.All.IT_TLBR_MA);
    Conf_Int.All.dprime_IT_TLBR_MA =...
        confidenceinterval(SDT.All.dprime_IT_TLBR_MA);

    %
    % Incongruent Bottom
    if isvalid4sdt(HitRate.All.IB_TLBR_MA,...
                   FARate.All.IB_TLBR_MA) == 1
        Exception.All = 1;
        Exception.Message = 'IB_TLBR_MA';
        break;
    end
    SDT.All.dprime_IB_TLBR_MA =...
        sensitivitycriterion4sdt(HitRate.All.IB_TLBR_MA,...
                                 FARate.All.IB_TLBR_MA);
    Conf_Int.All.dprime_IB_TLBR_MA =...
        confidenceinterval(SDT.All.dprime_IB_TLBR_MA);

    %
    % Congruent Top
    if isvalid4sdt(HitRate.All.CT_TLBR_MA,...
                   FARate.All.CT_TLBR_MA) == 1
        Exception.All = 1;
        Exception.Message = 'CT_TLBR_MA';
        break;
    end
    SDT.All.dprime_CT_TLBR_MA =...
        sensitivitycriterion4sdt(HitRate.All.CT_TLBR_MA,...
                                 FARate.All.CT_TLBR_MA);
    Conf_Int.All.dprime_CT_TLBR_MA =...
        confidenceinterval(SDT.All.dprime_CT_TLBR_MA);

    %
    % Congruent Bottom
    if isvalid4sdt(HitRate.All.CB_TLBR_MA,...
                   FARate.All.CB_TLBR_MA) == 1
        Exception.All = 1;
        Exception.Message = 'CB_TLBR_MA';
        break;
    end
    SDT.All.dprime_CB_TLBR_MA =...
        sensitivitycriterion4sdt(HitRate.All.CB_TLBR_MA,...
                                 FARate.All.CB_TLBR_MA);
    Conf_Int.All.dprime_CB_TLBR_MA =...
        confidenceinterval(SDT.All.dprime_CB_TLBR_MA);

    %
    % top-right bottom-left misaligned
    %
    % Incongruent Top
    if isvalid4sdt(HitRate.All.IT_TRBL_MA,...
                   FARate.All.IT_TRBL_MA) == 1
        Exception.All = 1;
        Exception.Message = 'IT_TRBL_MA';
        break;
    end
    SDT.All.dprime_IT_TRBL_MA =...
        sensitivitycriterion4sdt(HitRate.All.IT_TRBL_MA,...
                                 FARate.All.IT_TRBL_MA);
    Conf_Int.All.dprime_IT_TRBL_MA =...
        confidenceinterval(SDT.All.dprime_IT_TRBL_MA);

    %
    % Incongruent Bottom
    if isvalid4sdt(HitRate.All.IB_TRBL_MA,...
                   FARate.All.IB_TRBL_MA) == 1
        Exception.All = 1;
        Exception.Message = 'IB_TRBL_MA';
        break;
    end
    SDT.All.dprime_IB_TRBL_MA =...
        sensitivitycriterion4sdt(HitRate.All.IB_TRBL_MA,...
                                 FARate.All.IB_TRBL_MA);
    Conf_Int.All.dprime_IB_TRBL_MA =...
        confidenceinterval(SDT.All.dprime_IB_TRBL_MA);

    %
    % Congruent Top
    if isvalid4sdt(HitRate.All.CT_TRBL_MA,...
                   FARate.All.CT_TRBL_MA) == 1
        Exception.All = 1;
        Exception.Message = 'CT_TRBL_MA';
        break;
    end
    SDT.All.dprime_CT_TRBL_MA =...
        sensitivitycriterion4sdt(HitRate.All.CT_TRBL_MA,...
                                 FARate.All.CT_TRBL_MA);
    Conf_Int.All.dprime_CT_TRBL_MA =...
        confidenceinterval(SDT.All.dprime_CT_TRBL_MA);

    %
    % Congruent Bottom
    if isvalid4sdt(HitRate.All.CB_TRBL_MA,...
                   FARate.All.CB_TRBL_MA) == 1
        Exception.All = 1;
        Exception.Message = 'CB_TRBL_MA';
        break;
    end
    SDT.All.dprime_CB_TRBL_MA =...
        sensitivitycriterion4sdt(HitRate.All.CB_TRBL_MA,...
                                 FARate.All.CB_TRBL_MA);
    Conf_Int.All.dprime_CB_TRBL_MA =...
        confidenceinterval(SDT.All.dprime_CB_TRBL_MA);
    
    % Incongruent
    %
    % Aligned
    Conf_Int.All.dprime_I_A =...
        confidenceinterval([SDT.All.dprime_IT_LS_A; 
                            SDT.All.dprime_IT_RS_A;
                            SDT.All.dprime_IB_LS_A;
                            SDT.All.dprime_IB_RS_A]);

    % Misaligned (top-left bottom-right misaligned)
    Conf_Int.All.dprime_I_TLBR_MA =...
        confidenceinterval([SDT.All.dprime_IT_TLBR_MA;
                            SDT.All.dprime_IB_TLBR_MA]);

    % Misaligned (top-right bottom-left misaligned)
    Conf_Int.All.dprime_I_TRBL_MA =...
        confidenceinterval([SDT.All.dprime_IT_TRBL_MA;
                            SDT.All.dprime_IB_TRBL_MA]);
    
    % Misaligned
    Conf_Int.All.dprime_I_MA =...
        confidenceinterval([SDT.All.dprime_IT_TLBR_MA;
                            SDT.All.dprime_IB_TLBR_MA;
                            SDT.All.dprime_IT_TRBL_MA;
                            SDT.All.dprime_IB_TRBL_MA]);
                         

    % Congruent
    %
    % Aligned
    Conf_Int.All.dprime_C_A =...
        confidenceinterval([SDT.All.dprime_CT_LS_A;
                            SDT.All.dprime_CT_RS_A;
                            SDT.All.dprime_CB_LS_A;
                            SDT.All.dprime_CB_RS_A]);

    % Misaligned (top-left bottom-right misaligned)
    Conf_Int.All.dprime_C_TLBR_MA =...
        confidenceinterval([SDT.All.dprime_CT_TLBR_MA;
                            SDT.All.dprime_CB_TLBR_MA]);

    % Misaligned (top-right bottom-left misaligned)
    Conf_Int.All.dprime_C_TRBL_MA =...
        confidenceinterval([SDT.All.dprime_CT_TRBL_MA;
                            SDT.All.dprime_CB_TRBL_MA]);
                         
    % Misaligned
    Conf_Int.All.dprime_C_MA =...
        confidenceinterval([SDT.All.dprime_CT_TLBR_MA;
                            SDT.All.dprime_CB_TLBR_MA;
                            SDT.All.dprime_CT_TRBL_MA;
                            SDT.All.dprime_CB_TRBL_MA]);

    break;
end



%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 2: EXPERIMENT 1 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Percentage Error
% happy top + happy bottom
Pct_Acc_E1.HappyHappy_LS_A_bottom =...
    percent(Conf_Mx_E1.HappyHappy_LS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.HappyHappy_RS_A_bottom =...
    percent(Conf_Mx_E1.HappyHappy_RS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.HappyHappy_A_bottom =...
    percent(Conf_Mx_E1.HappyHappy_A_bottom, Expr.Happy, 2);

% happy bottom
Pct_Acc_E1.Happy_Bottom_LS =...
    percent(Conf_Mx_E1.Happy_Bottom_LS, Expr.Happy, 2);

Pct_Acc_E1.Happy_Bottom_RS =...
    percent(Conf_Mx_E1.Happy_Bottom_RS, Expr.Happy, 2);

Pct_Acc_E1.Happy_Bottom =...
    percent(Conf_Mx_E1.Happy_Bottom, Expr.Happy, 2);

% neutral top + happy bottom
Pct_Acc_E1.NeutralHappy_LS_A_bottom =...
    percent(Conf_Mx_E1.NeutralHappy_LS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.NeutralHappy_RS_A_bottom =...
    percent(Conf_Mx_E1.NeutralHappy_RS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.NeutralHappy_A_bottom =...
    percent(Conf_Mx_E1.NeutralHappy_A_bottom, Expr.Happy, 2);

% angry top + happy bottom
Pct_Acc_E1.AngryHappy_LS_A_bottom =...
    percent(Conf_Mx_E1.AngryHappy_LS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.AngryHappy_RS_A_bottom =...
    percent(Conf_Mx_E1.AngryHappy_RS_A_bottom, Expr.Happy, 2);

Pct_Acc_E1.AngryHappy_A_bottom =...
    percent(Conf_Mx_E1.AngryHappy_A_bottom, Expr.Happy, 2);

% angry top + angry bottom
Pct_Acc_E1.AngryAngry_LS_A_top =...
    percent(Conf_Mx_E1.AngryAngry_LS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryAngry_RS_A_top =...
    percent(Conf_Mx_E1.AngryAngry_RS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryAngry_A_top =...
    percent(Conf_Mx_E1.AngryAngry_A_top, Expr.Angry, 2);

% angry top
Pct_Acc_E1.Angry_Top_LS =...
    percent(Conf_Mx_E1.Angry_Top_LS, Expr.Angry, 2);

Pct_Acc_E1.Angry_Top_RS =...
    percent(Conf_Mx_E1.Angry_Top_RS, Expr.Angry, 2);

Pct_Acc_E1.Angry_Top =...
    percent(Conf_Mx_E1.Angry_Top, Expr.Angry, 2);

% angry top + neutral bottom
Pct_Acc_E1.AngryNeutral_LS_A_top =...
    percent(Conf_Mx_E1.AngryNeutral_LS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryNeutral_RS_A_top =...
    percent(Conf_Mx_E1.AngryNeutral_RS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryNeutral_A_top =...
    percent(Conf_Mx_E1.AngryNeutral_A_top, Expr.Angry, 2);

% angry top + happy bottom
Pct_Acc_E1.AngryHappy_LS_A_top =...
    percent(Conf_Mx_E1.AngryHappy_LS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryHappy_RS_A_top =...
    percent(Conf_Mx_E1.AngryHappy_RS_A_top, Expr.Angry, 2);

Pct_Acc_E1.AngryHappy_A_top =...
    percent(Conf_Mx_E1.AngryHappy_A_top, Expr.Angry, 2);

%%
% Average Accuracy
% happy top + happy bottom
Pct_Acc_E1.HappyHappy_LS_A_bottom_all =...
    mean(Pct_Acc_E1.HappyHappy_LS_A_bottom);

Pct_Acc_E1.HappyHappy_RS_A_bottom_all =...
    mean(Pct_Acc_E1.HappyHappy_RS_A_bottom);

Pct_Acc_E1.HappyHappy_A_bottom_all =...
    mean(Pct_Acc_E1.HappyHappy_A_bottom);

Conf_Int.Pct_Acc_E1.HappyHappy_LS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.HappyHappy_LS_A_bottom);

Conf_Int.Pct_Acc_E1.HappyHappy_RS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.HappyHappy_RS_A_bottom);

Conf_Int.Pct_Acc_E1.HappyHappy_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.HappyHappy_A_bottom);


% happy bottom
Pct_Acc_E1.Happy_Bottom_LS_all =...
    mean(Pct_Acc_E1.Happy_Bottom_LS);

Pct_Acc_E1.Happy_Bottom_RS_all =...
    mean(Pct_Acc_E1.Happy_Bottom_RS);

Pct_Acc_E1.Happy_Bottom_all =...
    mean(Pct_Acc_E1.Happy_Bottom);

Conf_Int.Pct_Acc_E1.Happy_Bottom_LS_all =...
    confidenceinterval(Pct_Acc_E1.Happy_Bottom_LS);

Conf_Int.Pct_Acc_E1.Happy_Bottom_RS_all =...
    confidenceinterval(Pct_Acc_E1.Happy_Bottom_RS);

Conf_Int.Pct_Acc_E1.Happy_Bottom_all =...
    confidenceinterval(Pct_Acc_E1.Happy_Bottom);


% neutral top + happy bottom
Pct_Acc_E1.NeutralHappy_LS_A_bottom_all =...
    mean(Pct_Acc_E1.NeutralHappy_LS_A_bottom);

Pct_Acc_E1.NeutralHappy_RS_A_bottom_all =...
    mean(Pct_Acc_E1.NeutralHappy_RS_A_bottom);

Pct_Acc_E1.NeutralHappy_A_bottom_all =...
    mean(Pct_Acc_E1.NeutralHappy_A_bottom);

Conf_Int.Pct_Acc_E1.NeutralHappy_LS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.NeutralHappy_LS_A_bottom);

Conf_Int.Pct_Acc_E1.NeutralHappy_RS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.NeutralHappy_RS_A_bottom);

Conf_Int.Pct_Acc_E1.NeutralHappy_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.NeutralHappy_A_bottom);


% angry top + happy bottom
Pct_Acc_E1.AngryHappy_LS_A_bottom_all =...
    mean(Pct_Acc_E1.AngryHappy_LS_A_bottom);

Pct_Acc_E1.AngryHappy_RS_A_bottom_all =...
    mean(Pct_Acc_E1.AngryHappy_RS_A_bottom);

Pct_Acc_E1.AngryHappy_A_bottom_all =...
    mean(Pct_Acc_E1.AngryHappy_A_bottom);

Conf_Int.Pct_Acc_E1.AngryHappy_LS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_LS_A_bottom);

Conf_Int.Pct_Acc_E1.AngryHappy_RS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_RS_A_bottom);

Conf_Int.Pct_Acc_E1.AngryHappy_A_bottom_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_A_bottom);


% angry top + angry bottom
Pct_Acc_E1.AngryAngry_LS_A_top_all =...
    mean(Pct_Acc_E1.AngryAngry_LS_A_top);

Pct_Acc_E1.AngryAngry_RS_A_top_all =...
    mean(Pct_Acc_E1.AngryAngry_RS_A_top);

Pct_Acc_E1.AngryAngry_A_top_all =...
    mean(Pct_Acc_E1.AngryAngry_A_top);

Conf_Int.Pct_Acc_E1.AngryAngry_LS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryAngry_LS_A_top);

Conf_Int.Pct_Acc_E1.AngryAngry_RS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryAngry_RS_A_top);

Conf_Int.Pct_Acc_E1.AngryAngry_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryAngry_A_top);


% angry top
Pct_Acc_E1.Angry_Top_LS_all =...
    mean(Pct_Acc_E1.Angry_Top_LS);

Pct_Acc_E1.Angry_Top_RS_all =...
    mean(Pct_Acc_E1.Angry_Top_RS);

Pct_Acc_E1.Angry_Top_all =...
    mean(Pct_Acc_E1.Angry_Top);

Conf_Int.Pct_Acc_E1.Angry_Top_LS_all =...
    confidenceinterval(Pct_Acc_E1.Angry_Top_LS);

Conf_Int.Pct_Acc_E1.Angry_Top_RS_all =...
    confidenceinterval(Pct_Acc_E1.Angry_Top_RS);

Conf_Int.Pct_Acc_E1.Angry_Top_all =...
    confidenceinterval(Pct_Acc_E1.Angry_Top);


% angry top + neutral bottom
Pct_Acc_E1.AngryNeutral_LS_A_top_all =...
    mean(Pct_Acc_E1.AngryNeutral_LS_A_top);

Pct_Acc_E1.AngryNeutral_RS_A_top_all =...
    mean(Pct_Acc_E1.AngryNeutral_RS_A_top);

Pct_Acc_E1.AngryNeutral_A_top_all =...
    mean(Pct_Acc_E1.AngryNeutral_A_top);

Conf_Int.Pct_Acc_E1.AngryNeutral_LS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryNeutral_LS_A_top);

Conf_Int.Pct_Acc_E1.AngryNeutral_RS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryNeutral_RS_A_top);

Conf_Int.Pct_Acc_E1.AngryNeutral_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryNeutral_A_top);


% angry top + happy bottom
Pct_Acc_E1.AngryHappy_LS_A_top_all =...
    mean(Pct_Acc_E1.AngryHappy_LS_A_top);

Pct_Acc_E1.AngryHappy_RS_A_top_all =...
    mean(Pct_Acc_E1.AngryHappy_RS_A_top);

Pct_Acc_E1.AngryHappy_A_top_all =...
    mean(Pct_Acc_E1.AngryHappy_A_top);

Conf_Int.Pct_Acc_E1.AngryHappy_LS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_LS_A_top);

Conf_Int.Pct_Acc_E1.AngryHappy_RS_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_RS_A_top);

Conf_Int.Pct_Acc_E1.AngryHappy_A_top_all =...
    confidenceinterval(Pct_Acc_E1.AngryHappy_A_top);

%%
% Reaction Time
%
% A reaction time of 1 corresponds to an incorrect decision
wrong = 1;

% convert CONFIDENCE to REACTION TIME
Confidence.E1 = 1 - Confidence.E1;

% happy top + happy bottom
Reaction_Time_E1.HappyHappy_LS_A_bottom =...
    mean_neq(reshape(Confidence.E1(1,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.HappyHappy_LS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.HappyHappy_LS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.HappyHappy_LS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.HappyHappy_LS_A_bottom);

Reaction_Time_E1.HappyHappy_RS_A_bottom =...
    mean_neq(reshape(Confidence.E1(9,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.HappyHappy_RS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.HappyHappy_RS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.HappyHappy_RS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.HappyHappy_RS_A_bottom);

Reaction_Time_E1.HappyHappy_A_bottom =...
    mean_neq([Reaction_Time_E1.HappyHappy_LS_A_bottom,...
              Reaction_Time_E1.HappyHappy_RS_A_bottom],...
             wrong, 2);
Reaction_Time_E1.HappyHappy_A_bottom_all =...
    mean_neq(Reaction_Time_E1.HappyHappy_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.HappyHappy_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.HappyHappy_A_bottom);
                    
% happy bottom
Reaction_Time_E1.Happy_Bottom_LS =...
    mean_neq(reshape(Confidence.E1(2,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.Happy_Bottom_LS_all =...
    mean_neq(Reaction_Time_E1.Happy_Bottom_LS, wrong);
Conf_Int.Reaction_Time_E1.Happy_Bottom_LS_all =...
    confidenceinterval(Reaction_Time_E1.Happy_Bottom_LS);

Reaction_Time_E1.Happy_Bottom_RS =...
    mean_neq(reshape(Confidence.E1(10,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.Happy_Bottom_RS_all =...
    mean_neq(Reaction_Time_E1.Happy_Bottom_RS, wrong);
Conf_Int.Reaction_Time_E1.Happy_Bottom_RS_all =...
    confidenceinterval(Reaction_Time_E1.Happy_Bottom_RS);

Reaction_Time_E1.Happy_Bottom =...
    mean_neq([Reaction_Time_E1.Happy_Bottom_LS,...
              Reaction_Time_E1.Happy_Bottom_RS],...
             wrong, 2);
Reaction_Time_E1.Happy_Bottom_all =...
    mean_neq(Reaction_Time_E1.Happy_Bottom, wrong);
Conf_Int.Reaction_Time_E1.Happy_Bottom_all =...
    confidenceinterval(Reaction_Time_E1.Happy_Bottom);


% neutral top + happy bottom
Reaction_Time_E1.NeutralHappy_LS_A_bottom =...
    mean_neq(reshape(Confidence.E1(3,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.NeutralHappy_LS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.NeutralHappy_LS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.NeutralHappy_LS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.NeutralHappy_LS_A_bottom);

Reaction_Time_E1.NeutralHappy_RS_A_bottom =...
    mean_neq(reshape(Confidence.E1(11,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.NeutralHappy_RS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.NeutralHappy_RS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.NeutralHappy_RS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.NeutralHappy_RS_A_bottom);

Reaction_Time_E1.NeutralHappy_A_bottom =...
    mean_neq([Reaction_Time_E1.NeutralHappy_LS_A_bottom,...
              Reaction_Time_E1.NeutralHappy_RS_A_bottom],...
             wrong, 2);
Reaction_Time_E1.NeutralHappy_A_bottom_all =...
    mean_neq(Reaction_Time_E1.NeutralHappy_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.NeutralHappy_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.NeutralHappy_A_bottom);


% angry top + happy bottom
Reaction_Time_E1.AngryHappy_LS_A_bottom =...
    mean_neq(reshape(Confidence.E1(4,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryHappy_LS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_LS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_LS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.AngryHappy_LS_A_bottom);

Reaction_Time_E1.AngryHappy_RS_A_bottom =...
    mean_neq(reshape(Confidence.E1(12,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryHappy_RS_A_bottom_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_RS_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_RS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.AngryHappy_RS_A_bottom);

Reaction_Time_E1.AngryHappy_A_bottom =...
    mean_neq([Reaction_Time_E1.AngryHappy_LS_A_bottom,...
              Reaction_Time_E1.AngryHappy_RS_A_bottom],...
             wrong, 2);
Reaction_Time_E1.AngryHappy_A_bottom_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_A_bottom, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_A_bottom_all =...
    confidenceinterval(Reaction_Time_E1.AngryHappy_A_bottom);


% angry top + angry bottom
Reaction_Time_E1.AngryAngry_LS_A_top =...
    mean_neq(reshape(Confidence.E1(5,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryAngry_LS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryAngry_LS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryAngry_LS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryAngry_LS_A_top);

Reaction_Time_E1.AngryAngry_RS_A_top =...
    mean_neq(reshape(Confidence.E1(13,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryAngry_RS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryAngry_RS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryAngry_RS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryAngry_RS_A_top);

Reaction_Time_E1.AngryAngry_A_top =...
    mean_neq([Reaction_Time_E1.AngryAngry_LS_A_top,...
              Reaction_Time_E1.AngryAngry_RS_A_top],...
             wrong, 2);
Reaction_Time_E1.AngryAngry_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryAngry_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryAngry_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryAngry_A_top);


% angry top
Reaction_Time_E1.Angry_Top_LS =...
    mean_neq(reshape(Confidence.E1(6,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.Angry_Top_LS_all =...
    mean_neq(Reaction_Time_E1.Angry_Top_LS, wrong);
Conf_Int.Reaction_Time_E1.Angry_Top_LS_all =...
    confidenceinterval(Reaction_Time_E1.Angry_Top_LS);

Reaction_Time_E1.Angry_Top_RS =...
    mean_neq(reshape(Confidence.E1(14,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.Angry_Top_RS_all =...
    mean_neq(Reaction_Time_E1.Angry_Top_RS, wrong);
Conf_Int.Reaction_Time_E1.Angry_Top_RS_all =...
    confidenceinterval(Reaction_Time_E1.Angry_Top_RS);

Reaction_Time_E1.Angry_Top =...
    mean_neq([Reaction_Time_E1.Angry_Top_LS,...
              Reaction_Time_E1.Angry_Top_RS],...
             wrong, 2);
Reaction_Time_E1.Angry_Top_all =...
    mean_neq(Reaction_Time_E1.Angry_Top, wrong);
Conf_Int.Reaction_Time_E1.Angry_Top_all =...
    confidenceinterval(Reaction_Time_E1.Angry_Top);


% angry top + neutral bottom
Reaction_Time_E1.AngryNeutral_LS_A_top =...
    mean_neq(reshape(Confidence.E1(7,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryNeutral_LS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryNeutral_LS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryNeutral_LS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryNeutral_LS_A_top);

Reaction_Time_E1.AngryNeutral_RS_A_top =...
    mean_neq(reshape(Confidence.E1(15,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryNeutral_RS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryNeutral_RS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryNeutral_RS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryNeutral_RS_A_top);

Reaction_Time_E1.AngryNeutral_A_top =...
    mean_neq([Reaction_Time_E1.AngryNeutral_LS_A_top,...
              Reaction_Time_E1.AngryNeutral_RS_A_top],...
             wrong, 2);
Reaction_Time_E1.AngryNeutral_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryNeutral_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryNeutral_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryNeutral_A_top);


% angry top + happy bottom
Reaction_Time_E1.AngryHappy_LS_A_top =...
    mean_neq(reshape(Confidence.E1(8,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryHappy_LS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_LS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_LS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryHappy_LS_A_top);

Reaction_Time_E1.AngryHappy_RS_A_top =...
    mean_neq(reshape(Confidence.E1(16,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E1.AngryHappy_RS_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_RS_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_RS_A_top_all =...
    confidenceinterval(Reaction_Time_E1.AngryHappy_RS_A_top);

Reaction_Time_E1.AngryHappy_A_top =...
    mean_neq([Reaction_Time_E1.AngryHappy_LS_A_top,...
              Reaction_Time_E1.AngryHappy_RS_A_top],...
             wrong, 2);
Reaction_Time_E1.AngryHappy_A_top_all =...
    mean_neq(Reaction_Time_E1.AngryHappy_A_top, wrong);
Conf_Int.Reaction_Time_E1.AngryHappy_A_top_all =...
    confidence_interval(Reaction_Time_E1.AngryHappy_A_top);

Confidence.E1 = 1 - Confidence.E1;

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 3: EXPERIMENT 3 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Percentage
% happy top + happy bottom
Pct_Acc_E3.HappyHappy_LS_A_bottom =...
    percent(Conf_Mx_E3.HappyHappy_LS_A_bottom, Expr.Happy, 2);

Pct_Acc_E3.HappyHappy_RS_A_bottom =...
    percent(Conf_Mx_E3.HappyHappy_RS_A_bottom, Expr.Happy, 2);

Pct_Acc_E3.HappyHappy_A_bottom =...
    percent(Conf_Mx_E3.HappyHappy_A_bottom, Expr.Happy, 2);


Pct_Acc_E3.HappyHappy_TLBR_MA_bottom =...
    percent(Conf_Mx_E3.HappyHappy_TLBR_MA_bottom, Expr.Happy, 2);

Pct_Acc_E3.HappyHappy_TRBL_MA_bottom =...
    percent(Conf_Mx_E3.HappyHappy_TRBL_MA_bottom, Expr.Happy, 2);

Pct_Acc_E3.HappyHappy_MA_bottom =...
    percent(Conf_Mx_E3.HappyHappy_MA_bottom, Expr.Happy, 2);

% angry top + happy bottom
Pct_Acc_E3.AngryHappy_LS_A_bottom =...
    percent(Conf_Mx_E3.AngryHappy_LS_A_bottom, Expr.Happy, 2);

Pct_Acc_E3.AngryHappy_RS_A_bottom =...
    percent(Conf_Mx_E3.AngryHappy_RS_A_bottom, Expr.Happy, 2);

Pct_Acc_E3.AngryHappy_A_bottom =...
    percent(Conf_Mx_E3.AngryHappy_A_bottom, Expr.Happy, 2);


Pct_Acc_E3.AngryHappy_TLBR_MA_bottom =...
    percent(Conf_Mx_E3.AngryHappy_TLBR_MA_bottom, Expr.Happy, 2);

Pct_Acc_E3.AngryHappy_TRBL_MA_bottom =...
    percent(Conf_Mx_E3.AngryHappy_TRBL_MA_bottom, Expr.Happy, 2);

Pct_Acc_E3.AngryHappy_MA_bottom =...
    percent(Conf_Mx_E3.AngryHappy_MA_bottom, Expr.Happy, 2);

% angry top + angry bottom
Pct_Acc_E3.AngryAngry_LS_A_top =...
    percent(Conf_Mx_E3.AngryAngry_LS_A_top, Expr.Angry, 2);

Pct_Acc_E3.AngryAngry_RS_A_top =...
    percent(Conf_Mx_E3.AngryAngry_RS_A_top, Expr.Angry, 2);

Pct_Acc_E3.AngryAngry_A_top =...
    percent(Conf_Mx_E3.AngryAngry_A_top, Expr.Angry, 2);


Pct_Acc_E3.AngryAngry_TLBR_MA_top =...
    percent(Conf_Mx_E3.AngryAngry_TLBR_MA_top, Expr.Angry, 2);

Pct_Acc_E3.AngryAngry_TRBL_MA_top =...
    percent(Conf_Mx_E3.AngryAngry_TRBL_MA_top, Expr.Angry, 2);

Pct_Acc_E3.AngryAngry_MA_top =...
    percent(Conf_Mx_E3.AngryAngry_MA_top, Expr.Angry, 2);

% angry top + happy bottom
Pct_Acc_E3.AngryHappy_LS_A_top =...
    percent(Conf_Mx_E3.AngryHappy_LS_A_top, Expr.Angry, 2);

Pct_Acc_E3.AngryHappy_RS_A_top =...
    percent(Conf_Mx_E3.AngryHappy_RS_A_top, Expr.Angry, 2);

Pct_Acc_E3.AngryHappy_A_top =...
    percent(Conf_Mx_E3.AngryHappy_A_top, Expr.Angry, 2);


Pct_Acc_E3.AngryHappy_TLBR_MA_top =...
    percent(Conf_Mx_E3.AngryHappy_TLBR_MA_top, Expr.Angry, 2);

Pct_Acc_E3.AngryHappy_TRBL_MA_top =...
    percent(Conf_Mx_E3.AngryHappy_TRBL_MA_top, Expr.Angry, 2);

Pct_Acc_E3.AngryHappy_MA_top =...
    percent(Conf_Mx_E3.AngryHappy_MA_top, Expr.Angry,2);

%%
% Experiment 3: Normal, Angry-Happy Breakdown
%
% Normal
Pct_Acc_E3.Normal_A =...
    [Pct_Acc_E3.HappyHappy_A_bottom;...
     Pct_Acc_E3.AngryAngry_A_top];

Pct_Acc_E3.Normal_TLBR_MA =...
    [Pct_Acc_E3.HappyHappy_TLBR_MA_bottom;...
     Pct_Acc_E3.AngryAngry_TLBR_MA_top];

Pct_Acc_E3.Normal_TRBL_MA =...
    [Pct_Acc_E3.HappyHappy_TRBL_MA_bottom;...
     Pct_Acc_E3.AngryAngry_TRBL_MA_top];

Pct_Acc_E3.Normal_MA =...
    [Pct_Acc_E3.HappyHappy_MA_bottom;...
     Pct_Acc_E3.AngryAngry_MA_top];
 
% Angry-Happy
Pct_Acc_E3.AngryHappy_A =...
    [Pct_Acc_E3.AngryHappy_A_bottom;...
     Pct_Acc_E3.AngryHappy_A_top];

Pct_Acc_E3.AngryHappy_TLBR_MA =...
    [Pct_Acc_E3.AngryHappy_TLBR_MA_bottom;...
     Pct_Acc_E3.AngryHappy_TLBR_MA_top];

Pct_Acc_E3.AngryHappy_TRBL_MA =...
    [Pct_Acc_E3.AngryHappy_TRBL_MA_bottom;...
     Pct_Acc_E3.AngryHappy_TRBL_MA_top];

Pct_Acc_E3.AngryHappy_MA =...
    [Pct_Acc_E3.AngryHappy_MA_bottom;...
     Pct_Acc_E3.AngryHappy_MA_top];

%%
% Average Accuracy
% happy top + happy bottom
Pct_Acc_E3.HappyHappy_LS_A_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_LS_A_bottom);

Pct_Acc_E3.HappyHappy_RS_A_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_RS_A_bottom);

Pct_Acc_E3.HappyHappy_A_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_A_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_LS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_LS_A_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_RS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_RS_A_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_A_bottom);


Pct_Acc_E3.HappyHappy_TLBR_MA_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_TLBR_MA_bottom);

Pct_Acc_E3.HappyHappy_TRBL_MA_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_TRBL_MA_bottom);

Pct_Acc_E3.HappyHappy_MA_bottom_all =...
    mean(Pct_Acc_E3.HappyHappy_MA_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_TLBR_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_TLBR_MA_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_TRBL_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_TRBL_MA_bottom);

Conf_Int.Pct_Acc_E3.HappyHappy_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.HappyHappy_MA_bottom);


% angry top + happy bottom
Pct_Acc_E3.AngryHappy_LS_A_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_LS_A_bottom);

Pct_Acc_E3.AngryHappy_RS_A_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_RS_A_bottom);

Pct_Acc_E3.AngryHappy_A_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_A_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_LS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_LS_A_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_RS_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_RS_A_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_A_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_A_bottom);


Pct_Acc_E3.AngryHappy_TLBR_MA_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_TLBR_MA_bottom);

Pct_Acc_E3.AngryHappy_TRBL_MA_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_TRBL_MA_bottom);

Pct_Acc_E3.AngryHappy_MA_bottom_all =...
    mean(Pct_Acc_E3.AngryHappy_MA_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_TLBR_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TLBR_MA_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_TRBL_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TRBL_MA_bottom);

Conf_Int.Pct_Acc_E3.AngryHappy_MA_bottom_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_MA_bottom);


% angry top + angry bottom
Pct_Acc_E3.AngryAngry_LS_A_top_all =...
    mean(Pct_Acc_E3.AngryAngry_LS_A_top);

Pct_Acc_E3.AngryAngry_RS_A_top_all =...
    mean(Pct_Acc_E3.AngryAngry_RS_A_top);

Pct_Acc_E3.AngryAngry_A_top_all =...
    mean(Pct_Acc_E3.AngryAngry_A_top);

Conf_Int.Pct_Acc_E3.AngryAngry_LS_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_LS_A_top);

Conf_Int.Pct_Acc_E3.AngryAngry_RS_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_RS_A_top);

Conf_Int.Pct_Acc_E3.AngryAngry_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_A_top);


Pct_Acc_E3.AngryAngry_TLBR_MA_top_all =...
    mean(Pct_Acc_E3.AngryAngry_TLBR_MA_top);

Pct_Acc_E3.AngryAngry_TRBL_MA_top_all =...
    mean(Pct_Acc_E3.AngryAngry_TRBL_MA_top);

Pct_Acc_E3.AngryAngry_MA_top_all =...
    mean(Pct_Acc_E3.AngryAngry_MA_top);

Conf_Int.Pct_Acc_E3.AngryAngry_TLBR_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_TLBR_MA_top);

Conf_Int.Pct_Acc_E3.AngryAngry_TRBL_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_TRBL_MA_top);

Conf_Int.Pct_Acc_E3.AngryAngry_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryAngry_MA_top);


% angry top + happy bottom
Pct_Acc_E3.AngryHappy_LS_A_top_all =...
    mean(Pct_Acc_E3.AngryHappy_LS_A_top);

Pct_Acc_E3.AngryHappy_RS_A_top_all =...
    mean(Pct_Acc_E3.AngryHappy_RS_A_top);

Pct_Acc_E3.AngryHappy_A_top_all =...
    mean(Pct_Acc_E3.AngryHappy_A_top);

Conf_Int.Pct_Acc_E3.AngryHappy_LS_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_LS_A_top);

Conf_Int.Pct_Acc_E3.AngryHappy_RS_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_RS_A_top);

Conf_Int.Pct_Acc_E3.AngryHappy_A_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_A_top);


Pct_Acc_E3.AngryHappy_TLBR_MA_top_all =...
    mean(Pct_Acc_E3.AngryHappy_TLBR_MA_top);

Pct_Acc_E3.AngryHappy_TRBL_MA_top_all =...
    mean(Pct_Acc_E3.AngryHappy_TRBL_MA_top);

Pct_Acc_E3.AngryHappy_MA_top_all =...
    mean(Pct_Acc_E3.AngryHappy_MA_top);

Conf_Int.Pct_Acc_E3.AngryHappy_TLBR_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TLBR_MA_top);

Conf_Int.Pct_Acc_E3.AngryHappy_TRBL_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TRBL_MA_top);

Conf_Int.Pct_Acc_E3.AngryHappy_MA_top_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_MA_top);

%%
% Experiment 3: Normal, Angry-Happy
%
% Normal
Pct_Acc_E3.Normal_A_all = mean(Pct_Acc_E3.Normal_A);
Pct_Acc_E3.Normal_TLBR_MA_all = mean(Pct_Acc_E3.Normal_TLBR_MA);
Pct_Acc_E3.Normal_TRBL_MA_all = mean(Pct_Acc_E3.Normal_TRBL_MA);
Pct_Acc_E3.Normal_MA_all = mean(Pct_Acc_E3.Normal_MA);

Conf_Int.Pct_Acc_E3.Normal_A_all =...
    confidenceinterval(Pct_Acc_E3.Normal_A);
Conf_Int.Pct_Acc_E3.Normal_TLBR_MA_all =...
    confidenceinterval(Pct_Acc_E3.Normal_TLBR_MA);
Conf_Int.Pct_Acc_E3.Normal_TRBL_MA_all =...
    confidenceinterval(Pct_Acc_E3.Normal_TRBL_MA);
Conf_Int.Pct_Acc_E3.Normal_MA_all =...
    confidenceinterval(Pct_Acc_E3.Normal_MA);

% Angry-Happy
Pct_Acc_E3.AngryHappy_A_all = mean(Pct_Acc_E3.AngryHappy_A);
Pct_Acc_E3.AngryHappy_TLBR_MA_all = mean(Pct_Acc_E3.AngryHappy_TLBR_MA);
Pct_Acc_E3.AngryHappy_TRBL_MA_all = mean(Pct_Acc_E3.AngryHappy_TRBL_MA);
Pct_Acc_E3.AngryHappy_MA_all = mean(Pct_Acc_E3.AngryHappy_MA);

Conf_Int.Pct_Acc_E3.AngryHappy_A_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_A);
Conf_Int.Pct_Acc_E3.AngryHappy_TLBR_MA_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TLBR_MA);
Conf_Int.Pct_Acc_E3.AngryHappy_TRBL_MA_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_TRBL_MA);
Conf_Int.Pct_Acc_E3.AngryHappy_MA_all =...
    confidenceinterval(Pct_Acc_E3.AngryHappy_MA);

%%
% Reaction Time
Confidence.E3 = 1 - Confidence.E3;

% happy top + happy bottom
Reaction_Time_E3.HappyHappy_LS_A_bottom =...
    mean_neq(reshape(Confidence.E3(1,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.HappyHappy_LS_A_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_LS_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_LS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_LS_A_bottom);

Reaction_Time_E3.HappyHappy_RS_A_bottom =...
    mean_neq(reshape(Confidence.E3(2,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.HappyHappy_RS_A_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_RS_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_RS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_RS_A_bottom);

Reaction_Time_E3.HappyHappy_A_bottom =...
    mean_neq([Reaction_Time_E3.HappyHappy_LS_A_bottom,...
              Reaction_Time_E3.HappyHappy_RS_A_bottom],...
             wrong, 2);
Reaction_Time_E3.HappyHappy_A_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_A_bottom);


Reaction_Time_E3.HappyHappy_TLBR_MA_bottom =...
    mean_neq(reshape(Confidence.E3(3,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.HappyHappy_TLBR_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_TLBR_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_TLBR_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_TLBR_MA_bottom);

Reaction_Time_E3.HappyHappy_TRBL_MA_bottom =...
    mean_neq(reshape(Confidence.E3(4,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.HappyHappy_TRBL_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_TRBL_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_TRBL_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_TRBL_MA_bottom);

Reaction_Time_E3.HappyHappy_MA_bottom =...
    mean_neq([Reaction_Time_E3.HappyHappy_TLBR_MA_bottom,...
              Reaction_Time_E3.HappyHappy_TRBL_MA_bottom],...
             wrong, 2);
Reaction_Time_E3.HappyHappy_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.HappyHappy_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.HappyHappy_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.HappyHappy_MA_bottom);


% angry top + happy bottom
Reaction_Time_E3.AngryHappy_LS_A_bottom =...
    mean_neq(reshape(Confidence.E3(5,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_LS_A_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_LS_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_LS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_LS_A_bottom);

Reaction_Time_E3.AngryHappy_RS_A_bottom =...
    mean_neq(reshape(Confidence.E3(6,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_RS_A_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_RS_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_RS_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_RS_A_bottom);

Reaction_Time_E3.AngryHappy_A_bottom =...
    mean_neq([Reaction_Time_E3.AngryHappy_LS_A_bottom,...
              Reaction_Time_E3.AngryHappy_RS_A_bottom],...
             wrong, 2);
Reaction_Time_E3.AngryHappy_A_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_A_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_A_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_A_bottom);


Reaction_Time_E3.AngryHappy_TLBR_MA_bottom =...
    mean_neq(reshape(Confidence.E3(7,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_TLBR_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TLBR_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_TLBR_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TLBR_MA_bottom);

Reaction_Time_E3.AngryHappy_TRBL_MA_bottom =...
    mean_neq(reshape(Confidence.E3(8,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_TRBL_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TRBL_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_TRBL_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TRBL_MA_bottom);

Reaction_Time_E3.AngryHappy_MA_bottom =...
    mean_neq([Reaction_Time_E3.AngryHappy_TLBR_MA_bottom,...
              Reaction_Time_E3.AngryHappy_TRBL_MA_bottom],...
             wrong, 2);
Reaction_Time_E3.AngryHappy_MA_bottom_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_MA_bottom, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_MA_bottom_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_MA_bottom);

% angry top + angry bottom
Reaction_Time_E3.AngryAngry_LS_A_top =...
    mean_neq(reshape(Confidence.E3(9,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryAngry_LS_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_LS_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_LS_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_LS_A_top);

Reaction_Time_E3.AngryAngry_RS_A_top =...
    mean_neq(reshape(Confidence.E3(10,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryAngry_RS_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_RS_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_RS_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_RS_A_top);

Reaction_Time_E3.AngryAngry_A_top =...
    mean_neq([Reaction_Time_E3.AngryAngry_LS_A_top,...
              Reaction_Time_E3.AngryAngry_RS_A_top],...
             wrong, 2);
Reaction_Time_E3.AngryAngry_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_A_top);


Reaction_Time_E3.AngryAngry_TLBR_MA_top =...
    mean_neq(reshape(Confidence.E3(11,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryAngry_TLBR_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_TLBR_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_TLBR_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_TLBR_MA_top);

Reaction_Time_E3.AngryAngry_TRBL_MA_top =...
    mean_neq(reshape(Confidence.E3(12,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryAngry_TRBL_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_TRBL_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_TRBL_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_TRBL_MA_top);

Reaction_Time_E3.AngryAngry_MA_top =...
    mean_neq([Reaction_Time_E3.AngryAngry_TLBR_MA_top,...
              Reaction_Time_E3.AngryAngry_TRBL_MA_top],...
             wrong, 2);
Reaction_Time_E3.AngryAngry_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryAngry_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryAngry_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryAngry_MA_top);

% angry top + happy bottom
Reaction_Time_E3.AngryHappy_LS_A_top =...
    mean_neq(reshape(Confidence.E3(13,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_LS_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_LS_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_LS_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_LS_A_top);

Reaction_Time_E3.AngryHappy_RS_A_top =...
    mean_neq(reshape(Confidence.E3(14,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_RS_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_RS_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_RS_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_RS_A_top);

Reaction_Time_E3.AngryHappy_A_top =...
    mean_neq([Reaction_Time_E3.AngryHappy_LS_A_top,...
              Reaction_Time_E3.AngryHappy_RS_A_top],...
             wrong, 2);
Reaction_Time_E3.AngryHappy_A_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_A_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_A_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_A_top);


Reaction_Time_E3.AngryHappy_TLBR_MA_top =...
    mean_neq(reshape(Confidence.E3(15,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_TLBR_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TLBR_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_TLBR_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TLBR_MA_top);

Reaction_Time_E3.AngryHappy_TRBL_MA_top =...
    mean_neq(reshape(Confidence.E3(16,:,:), n.Subsets, n.Runs2),...
             wrong, 2);
Reaction_Time_E3.AngryHappy_TRBL_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TRBL_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_TRBL_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TRBL_MA_top);

Reaction_Time_E3.AngryHappy_MA_top =...
    mean_neq([Reaction_Time_E3.AngryHappy_TLBR_MA_top,...
              Reaction_Time_E3.AngryHappy_TRBL_MA_top],...
             wrong, 2);
Reaction_Time_E3.AngryHappy_MA_top_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_MA_top, wrong);
Conf_Int.Reaction_Time_E3.AngryHappy_MA_top_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_MA_top);

%%
% Experiment 3: Normal, Angry-Happy
%
% Normal
Reaction_Time_E3.Normal_A =...
    [Reaction_Time_E3.HappyHappy_A_bottom;...
     Reaction_Time_E3.AngryAngry_A_top];
Reaction_Time_E3.Normal_TLBR_MA =...
    [Reaction_Time_E3.HappyHappy_TLBR_MA_bottom;...
     Reaction_Time_E3.AngryAngry_TLBR_MA_top];
Reaction_Time_E3.Normal_TRBL_MA =...
    [Reaction_Time_E3.HappyHappy_TRBL_MA_bottom;...
     Reaction_Time_E3.AngryAngry_TRBL_MA_top];
Reaction_Time_E3.Normal_MA =...
    [Reaction_Time_E3.HappyHappy_MA_bottom;...
     Reaction_Time_E3.AngryAngry_MA_top];

Reaction_Time_E3.Normal_A_all ...
    = mean_neq(Reaction_Time_E3.Normal_A, wrong, 2);
Reaction_Time_E3.Normal_TLBR_MA_all ...
    = mean_neq(Reaction_Time_E3.Normal_TLBR_MA, wrong, 2);
Reaction_Time_E3.Normal_TRBL_MA_all ...
    = mean_neq(Reaction_Time_E3.Normal_TRBL_MA, wrong, 2);
Reaction_Time_E3.Normal_MA_all ...
    = mean_neq(Reaction_Time_E3.Normal_MA, wrong, 2);

Conf_Int.Reaction_Time_E3.Normal_A_all =...
    confidenceinterval(Reaction_Time_E3.Normal_A);
Conf_Int.Reaction_Time_E3.Normal_TLBR_MA_all =...
    confidenceinterval(Reaction_Time_E3.Normal_TLBR_MA);
Conf_Int.Reaction_Time_E3.Normal_TRBL_MA_all =...
    confidenceinterval(Reaction_Time_E3.Normal_TRBL_MA);
Conf_Int.Reaction_Time_E3.Normal_MA_all =...
    confidenceinterval(Reaction_Time_E3.Normal_MA);

% Angry-Happy
Reaction_Time_E3.AngryHappy_A =...
    [Reaction_Time_E3.AngryHappy_A_bottom;...
     Reaction_Time_E3.AngryHappy_A_top];
Reaction_Time_E3.AngryHappy_TLBR_MA =...
    [Reaction_Time_E3.AngryHappy_TLBR_MA_bottom;...
     Reaction_Time_E3.AngryHappy_TLBR_MA_top];
Reaction_Time_E3.AngryHappy_TRBL_MA =...
    [Reaction_Time_E3.AngryHappy_TRBL_MA_bottom;...
     Reaction_Time_E3.AngryHappy_TRBL_MA_top];
Reaction_Time_E3.AngryHappy_MA =...
    [Reaction_Time_E3.AngryHappy_MA_bottom;...
     Reaction_Time_E3.AngryHappy_MA_top];

Reaction_Time_E3.AngryHappy_A_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_A, wrong, 2);
Reaction_Time_E3.AngryHappy_TLBR_MA_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TLBR_MA, wrong, 2);
Reaction_Time_E3.AngryHappy_TRBL_MA_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_TRBL_MA, wrong, 2);
Reaction_Time_E3.AngryHappy_MA_all =...
    mean_neq(Reaction_Time_E3.AngryHappy_MA, wrong, 2);

Conf_Int.Reaction_Time_E3.AngryHappy_A_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_A);
Conf_Int.Reaction_Time_E3.AngryHappy_TLBR_MA_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TLBR_MA);
Conf_Int.Reaction_Time_E3.AngryHappy_TRBL_MA_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_TRBL_MA);
Conf_Int.Reaction_Time_E3.AngryHappy_MA_all =...
    confidenceinterval(Reaction_Time_E3.AngryHappy_MA);

Confidence.E3 = 1 - Confidence.E3;