% Script
%
% DATAANALYSIS
%   Notes:
%   07/03/2013
%     - analyzes data from testing and simulations 1, 2 and 3
%
%   Functions called:
%       confidenceinterval
%       congruencyrates
%       isvalid4sdt
%       sensitivitycriterion4sdt
%       percent
%       meanexclude


%%%%%%%%%%%
% TESTING %
%%%%%%%%%%%
%
% Percent accuracy (by expression)
%
% Noncomposite face images
%
% left-shifted
percentAccuracy.expression.NC_LS_A =...
    100*diag(confusionMatrix.NC_LS_A)./sum(confusionMatrix.NC_LS_A, 2);
% right-shifted
percentAccuracy.expression.NC_RS_A =...
    100*diag(confusionMatrix.NC_RS_A)./sum(confusionMatrix.NC_RS_A, 2);
% all
percentAccuracy.expression.NC_A =...
    100*diag(confusionMatrix.NC_A)./sum(confusionMatrix.NC_A, 2);

% Top-half face images
%
% left-shifted
percentAccuracy.expression.TH_LS_A =...
    100*diag(confusionMatrix.TH_LS_A)./sum(confusionMatrix.TH_LS_A, 2);
% right-shifted
percentAccuracy.expression.TH_RS_A =...
    100*diag(confusionMatrix.TH_RS_A)./sum(confusionMatrix.TH_RS_A, 2);
% all
percentAccuracy.expression.TH_A =...
    100*diag(confusionMatrix.TH_A)./sum(confusionMatrix.TH_A, 2);

% Bottom-half face images
%
% left-shifted
percentAccuracy.expression.BH_LS_A =...
    100*diag(confusionMatrix.BH_LS_A)./sum(confusionMatrix.BH_LS_A, 2);
% right-shifted
percentAccuracy.expression.BH_RS_A =...
    100*diag(confusionMatrix.BH_RS_A)./sum(confusionMatrix.BH_RS_A, 2);
% all
percentAccuracy.expression.BH_A =...
    100*diag(confusionMatrix.BH_A)./sum(confusionMatrix.BH_A, 2);




% Percent accuracy (overall)
%
% Noncomposite face images
%
% left-shifted
percentAccuracy.all.NC_LS_A = mean(percentAccuracy.NC_LS_A(:));
% right-shifted
percentAccuracy.all.NC_RS_A = mean(percentAccuracy.NC_RS_A(:));
% all
percentAccuracy.all.NC_A = mean(percentAccuracy.NC_A(:));

% left-shifted
confidenceInterval.percentAccuracy.all.NC_LS_A =...
    confidenceinterval(mean(percentAccuracy.NC_LS_A, 2));
% right-shifted
confidenceInterval.percentAccuracy.all.NC_RS_A =...
    confidenceinterval(mean(percentAccuracy.NC_RS_A, 2));
% all
confidenceInterval.percentAccuracy.all.NC_A =...
    confidenceinterval(mean(percentAccuracy.NC_A, 2));


% Top-half face images
%
% left-shifted
percentAccuracy.all.TH_LS_A = mean(percentAccuracy.TH_LS_A(:));
% right-shifted
percentAccuracy.all.TH_RS_A = mean(percentAccuracy.TH_RS_A(:));
% all
percentAccuracy.all.TH_A = mean(percentAccuracy.TH_A(:));

% left-shifted
confidenceInterval.percentAccuracy.all.TH_LS_A =...
    confidenceinterval(mean(percentAccuracy.TH_LS_A, 2));
% right-shifted
confidenceInterval.percentAccuracy.all.TH_RS_A =...
    confidenceinterval(mean(percentAccuracy.TH_RS_A, 2));
% all
confidenceInterval.percentAccuracy.all.TH_A =...
    confidenceinterval(mean(percentAccuracy.TH_A, 2));


% Bottom-half face images
% left-shifted
percentAccuracy.all.BH_LS_A = mean(percentAccuracy.BH_LS_A(:));
% right-shifted
percentAccuracy.all.BH_RS_A = mean(percentAccuracy.BH_RS_A(:));
% all
percentAccuracy.all.BH_A = mean(percentAccuracy.BH_A(:));

% left-shifted
confidenceInterval.percentAccuracy.all.BH_LS_A =...
    confidenceinterval(mean(percentAccuracy.BH_LS_A, 2));
% right-shifted
confidenceInterval.percentAccuracy.all.BH_RS_A =...
    confidenceinterval(mean(percentAccuracy.BH_RS_A, 2));
% all
confidenceInterval.percentAccuracy.all.BH_A =...
    confidenceinterval(mean(percentAccuracy.BH_A, 2));


%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 1 (COMPLETE COMPOSITE PARADIGM) %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cd([pwd, '/Signal Detection Theory'])

% Signal Detection Theory
%
% rates
%
% left-shifted aligned
[SDT.all.hitRates.IT_LS_A, SDT.all.FARates.IT_LS_A,...
    SDT.all.hitRate.IT_LS_A, SDT.all.FARate.IT_LS_A,...
 SDT.all.hitRates.IB_LS_A, SDT.all.FARates.IB_LS_A,...
    SDT.all.hitRate.IB_LS_A, SDT.all.FARate.IB_LS_A,...
 SDT.all.hitRates.CT_LS_A, SDT.all.FARates.CT_LS_A,...
    SDT.all.hitRate.CT_LS_A, SDT.all.FARate.CT_LS_A,...
 SDT.all.hitRates.CB_LS_A, SDT.all.FARates.CB_LS_A,...
    SDT.all.hitRate.CB_LS_A, SDT.all.FARate.CB_LS_A] =...
congruencyrates(rates.all.LS_A,...
                n.selectedTrials.all,...
                n.subsets);
%
% right-shifted aligned
[SDT.all.hitRates.IT_RS_A, SDT.all.FARates.IT_RS_A,...
    SDT.all.hitRate.IT_RS_A, SDT.all.FARate.IT_RS_A,...
 SDT.all.hitRates.IB_RS_A, SDT.all.FARates.IB_RS_A,...
    SDT.all.hitRate.IB_RS_A, SDT.all.FARate.IB_RS_A,...
 SDT.all.hitRates.CT_RS_A, SDT.all.FARates.CT_RS_A,...
    SDT.all.hitRate.CT_RS_A, SDT.all.FARate.CT_RS_A,...
 SDT.all.hitRates.CB_RS_A, SDT.all.FARates.CB_RS_A,...
    SDT.all.hitRate.CB_RS_A, SDT.all.FARate.CB_RS_A] =...
congruencyrates(rates.all.RS_A,...
                n.selectedTrials.all,...
                n.subsets);
%
% top-left bottom-right misaligned
[SDT.all.hitRates.IT_TLBR_MA, SDT.all.FARates.IT_TLBR_MA,...
    SDT.all.hitRate.IT_TLBR_MA, SDT.all.FARate.IT_TLBR_MA,...
 SDT.all.hitRates.IB_TLBR_MA, SDT.all.FARates.IB_TLBR_MA,...
    SDT.all.hitRate.IB_TLBR_MA, SDT.all.FARate.IB_TLBR_MA,...
 SDT.all.hitRates.CT_TLBR_MA, SDT.all.FARates.CT_TLBR_MA,...
    SDT.all.hitRate.CT_TLBR_MA, SDT.all.FARate.CT_TLBR_MA,...
 SDT.all.hitRates.CB_TLBR_MA, SDT.all.FARates.CB_TLBR_MA,...
    SDT.all.hitRate.CB_TLBR_MA, SDT.all.FARate.CB_TLBR_MA] =...
congruencyrates(rates.all.TLBR_MA,...
                n.selectedTrials.all,...
                n.subsets);
%
% top-right bottom-left misaligned
[SDT.all.hitRates.IT_TRBL_MA, SDT.all.FARates.IT_TRBL_MA,...
    SDT.all.hitRate.IT_TRBL_MA, SDT.all.FARate.IT_TRBL_MA,...
 SDT.all.hitRates.IB_TRBL_MA, SDT.all.FARates.IB_TRBL_MA,...
    SDT.all.hitRate.IB_TRBL_MA, SDT.all.FARate.IB_TRBL_MA,...
 SDT.all.hitRates.CT_TRBL_MA, SDT.all.FARates.CT_TRBL_MA,...
    SDT.all.hitRate.CT_TRBL_MA, SDT.all.FARate.CT_TRBL_MA,...
 SDT.all.hitRates.CB_TRBL_MA, SDT.all.FARates.CB_TRBL_MA,...
    SDT.all.hitRate.CB_TRBL_MA, SDT.all.FARate.CB_TRBL_MA] =...
congruencyrates(rates.all.TRBL_MA,...
                n.selectedTrials.all,...
                n.subsets);


% criterion c & d-prime
%
% variable to indicate whether signal detection theory
% computations can be applied to the data
SDT.all.failure = 0;
while(1)
    % left-shifted aligned
    %
    % Incongruent Top
    if isvalid4sdt(SDT.all.hitRates.IT_LS_A,...
                   SDT.all.FARates.IT_LS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IT_LS_A';
        break;
    end

    SDT.all.dprimes.IT_LS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IT_LS_A,...
                                 SDT.all.FARates.IT_LS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.IT_LS_A =...
        confidenceinterval(SDT.all.dprimes.IT_LS_A);


    % Incongruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IB_LS_A,...
                   SDT.all.FARates.IB_LS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IB_LS_A';
        break;
    end

    SDT.all.dprimes.IB_LS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IB_LS_A,...
                                 SDT.all.FARates.IB_LS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.IB_LS_A =...
        confidenceinterval(SDT.all.dprimes.IB_LS_A);


    % Congruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CT_LS_A,...
                   SDT.all.FARates.CT_LS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CT_LS_A';
        break;
    end

    SDT.all.dprimes.CT_LS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CT_LS_A,...
                                 SDT.all.FARates.CT_LS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.CT_LS_A =...
        confidenceinterval(SDT.all.dprimes.CT_LS_A);


    % Congruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CB_LS_A,...
                   SDT.all.FARates.CB_LS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CB_LS_A';
        break;
    end

    SDT.all.dprimes.CB_LS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CB_LS_A,...
                                 SDT.all.FARates.CB_LS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.CB_LS_A =...
        confidenceinterval(SDT.all.dprimes.CB_LS_A);




    % right-shifted aligned
    %
    % Incongruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IT_RS_A,...
                   SDT.all.FARates.IT_RS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IT_RS_A';
        break;
    end

    SDT.all.dprimes.IT_RS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IT_RS_A,...
                                 SDT.all.FARates.IT_RS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.IT_RS_A =...
        confidenceinterval(SDT.all.dprimes.IT_RS_A);


    % Incongruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IB_RS_A,...
                   SDT.all.FARates.IB_RS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IB_RS_A';
        break;
    end

    SDT.all.dprimes.IB_RS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IB_RS_A,...
                                 SDT.all.FARates.IB_RS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.IB_RS_A =...
        confidenceinterval(SDT.all.dprimes.IB_RS_A);


    % Congruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CT_RS_A,...
                   SDT.all.FARates.CT_RS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CT_RS_A';
        break;
    end

    SDT.all.dprimes.CT_RS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CT_RS_A,...
                                 SDT.all.FARates.CT_RS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.CT_RS_A =...
        confidenceinterval(SDT.all.dprimes.CT_RS_A);


    % Congruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CB_RS_A,...
                   SDT.all.FARates.CB_RS_A) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CB_RS_A';
        break;
    end

    SDT.all.dprimes.CB_RS_A =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CB_RS_A,...
                                 SDT.all.FARates.CB_RS_A);

    cd ..
    confidenceInterval.SDT.all.dprime.CB_RS_A =...
        confidenceinterval(SDT.all.dprimes.CB_RS_A);




    % top-left bottom-right misaligned
    %
    % Incongruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IT_TLBR_MA,...
                   SDT.all.FARates.IT_TLBR_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IT_TLBR_MA';
        break;
    end

    SDT.all.dprimes.IT_TLBR_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IT_TLBR_MA,...
                                 SDT.all.FARates.IT_TLBR_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.IT_TLBR_MA =...
        confidenceinterval(SDT.all.dprimes.IT_TLBR_MA);


    % Incongruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IB_TLBR_MA,...
                   SDT.all.FARates.IB_TLBR_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IB_TLBR_MA';
        break;
    end

    SDT.all.dprimes.IB_TLBR_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IB_TLBR_MA,...
                                 SDT.all.FARates.IB_TLBR_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.IB_TLBR_MA =...
        confidenceinterval(SDT.all.dprimes.IB_TLBR_MA);


    % Congruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CT_TLBR_MA,...
                   SDT.all.FARates.CT_TLBR_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CT_TLBR_MA';
        break;
    end

    SDT.all.dprimes.CT_TLBR_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CT_TLBR_MA,...
                                 SDT.all.FARates.CT_TLBR_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.CT_TLBR_MA =...
        confidenceinterval(SDT.all.dprimes.CT_TLBR_MA);


    % Congruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CB_TLBR_MA,...
                   SDT.all.FARates.CB_TLBR_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CB_TLBR_MA';
        break;
    end

    SDT.all.dprimes.CB_TLBR_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CB_TLBR_MA,...
                                 SDT.all.FARates.CB_TLBR_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.CB_TLBR_MA =...
        confidenceinterval(SDT.all.dprimes.CB_TLBR_MA);




    % top-right bottom-left misaligned
    %
    % Incongruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IT_TRBL_MA,...
                   SDT.all.FARates.IT_TRBL_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IT_TRBL_MA';
        break;
    end

    SDT.all.dprimes.IT_TRBL_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IT_TRBL_MA,...
                                 SDT.all.FARates.IT_TRBL_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.IT_TRBL_MA =...
        confidenceinterval(SDT.all.dprimes.IT_TRBL_MA);


    % Incongruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.IB_TRBL_MA,...
                   SDT.all.FARates.IB_TRBL_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'IB_TRBL_MA';
        break;
    end

    SDT.all.dprimes.IB_TRBL_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.IB_TRBL_MA,...
                                 SDT.all.FARates.IB_TRBL_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.IB_TRBL_MA =...
        confidenceinterval(SDT.all.dprimes.IB_TRBL_MA);


    % Congruent Top
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CT_TRBL_MA,...
                   SDT.all.FARates.CT_TRBL_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CT_TRBL_MA';
        break;
    end

    SDT.all.dprimes.CT_TRBL_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CT_TRBL_MA,...
                                 SDT.all.FARates.CT_TRBL_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.CT_TRBL_MA =...
        confidenceinterval(SDT.all.dprimes.CT_TRBL_MA);


    % Congruent Bottom
    cd([pwd, '/Signal Detection Theory'])
    if isvalid4sdt(SDT.all.hitRates.CB_TRBL_MA,...
                   SDT.all.FARates.CB_TRBL_MA) == 1
        SDT.all.failure = 1;
        SDT.all.failurePoint = 'CB_TRBL_MA';
        break;
    end

    SDT.all.dprimes.CB_TRBL_MA =...
        sensitivitycriterion4sdt(SDT.all.hitRates.CB_TRBL_MA,...
                                 SDT.all.FARates.CB_TRBL_MA);

    cd ..
    confidenceInterval.SDT.all.dprime.CB_TRBL_MA =...
        confidenceinterval(SDT.all.dprimes.CB_TRBL_MA);




    % Incongruent
    %
    % Aligned
    confidenceInterval.SDT.all.dprime.I_A =...
        confidenceinterval([SDT.all.dprimes.IT_LS_A; 
                            SDT.all.dprimes.IT_RS_A;
                            SDT.all.dprimes.IB_LS_A;
                            SDT.all.dprimes.IB_RS_A]);

    % Misaligned (top-left bottom-right misaligned)
    confidenceInterval.SDT.all.dprime.I_TLBR_MA =...
        confidenceinterval([SDT.all.dprimes.IT_TLBR_MA;
                            SDT.all.dprimes.IB_TLBR_MA]);

    % Misaligned (top-right bottom-left misaligned)
    confidenceInterval.SDT.all.dprime.I_TRBL_MA =...
        confidenceinterval([SDT.all.dprimes.IT_TRBL_MA;
                            SDT.all.dprimes.IB_TRBL_MA]);
    
    % Misaligned
    confidenceInterval.SDT.all.dprime.I_MA =...
        confidenceinterval([SDT.all.dprimes.IT_TLBR_MA;
                            SDT.all.dprimes.IB_TLBR_MA;
                            SDT.all.dprimes.IT_TRBL_MA;
                            SDT.all.dprimes.IB_TRBL_MA]);
 



    % Congruent
    %
    % Aligned
    confidenceInterval.SDT.all.dprime.C_A =...
        confidenceinterval([SDT.all.dprimes.CT_LS_A;
                            SDT.all.dprimes.CT_RS_A;
                            SDT.all.dprimes.CB_LS_A;
                            SDT.all.dprimes.CB_RS_A]);

    % Misaligned (top-left bottom-right misaligned)
    confidenceInterval.SDT.all.dprime.C_TLBR_MA =...
        confidenceinterval([SDT.all.dprimes.CT_TLBR_MA;
                            SDT.all.dprimes.CB_TLBR_MA]);

    % Misaligned (top-right bottom-left misaligned)
    confidenceInterval.SDT.all.dprime.C_TRBL_MA =...
        confidenceinterval([SDT.all.dprimes.CT_TRBL_MA;
                            SDT.all.dprimes.CB_TRBL_MA]);
                         
    % Misaligned
    confidenceInterval.SDT.all.dprime.C_MA =...
        confidenceinterval([SDT.all.dprimes.CT_TLBR_MA;
                            SDT.all.dprimes.CB_TLBR_MA;
                            SDT.all.dprimes.CT_TRBL_MA;
                            SDT.all.dprimes.CB_TRBL_MA]);
    break;
end



%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 2 (TANAKA ET AL. EXPERIMENT 1) %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Percent accuracy
%
% happy top + happy bottom
percentAccuracy.E1.happyHappy_LS_A_bottom =...
    percent(confusionVectors.E1.happyHappy_LS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.happyHappy_RS_A_bottom =...
    percent(confusionVectors.E1.happyHappy_RS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.happyHappy_A_bottom =...
    percent(confusionVectors.E1.happyHappy_A_bottom,...
            expression.happy, 2);

% happy bottom
percentAccuracy.E1.happyBottom_LS =...
    percent(confusionVectors.E1.happyBottom_LS,...
            expression.happy, 2);

percentAccuracy.E1.happyBottom_RS =...
    percent(confusionVectors.E1.happyBottom_RS,...
            expression.happy, 2);

percentAccuracy.E1.happyBottom =...
    percent(confusionVectors.E1.happyBottom,...
            expression.happy, 2);

% neutral top + happy bottom
percentAccuracy.E1.neutralHappy_LS_A_bottom =...
    percent(confusionVectors.E1.neutralHappy_LS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.neutralHappy_RS_A_bottom =...
    percent(confusionVectors.E1.neutralHappy_RS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.neutralHappy_A_bottom =...
    percent(confusionVectors.E1.neutralHappy_A_bottom,...
            expression.happy, 2);

% angry top + happy bottom
percentAccuracy.E1.angryHappy_LS_A_bottom =...
    percent(confusionVectors.E1.angryHappy_LS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.angryHappy_RS_A_bottom =...
    percent(confusionVectors.E1.angryHappy_RS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E1.angryHappy_A_bottom =...
    percent(confusionVectors.E1.angryHappy_A_bottom,...
            expression.happy, 2);




% angry top + angry bottom
percentAccuracy.E1.angryAngry_LS_A_top =...
    percent(confusionVectors.E1.angryAngry_LS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryAngry_RS_A_top =...
    percent(confusionVectors.E1.angryAngry_RS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryAngry_A_top =...
    percent(confusionVectors.E1.angryAngry_A_top,...
            expression.angry, 2);

% angry top
percentAccuracy.E1.angryTop_LS =...
    percent(confusionVectors.E1.angryTop_LS,...
            expression.angry, 2);

percentAccuracy.E1.angryTop_RS =...
    percent(confusionVectors.E1.angryTop_RS,...
            expression.angry, 2);

percentAccuracy.E1.angryTop =...
    percent(confusionVectors.E1.angryTop,...
            expression.angry, 2);

% angry top + neutral bottom
percentAccuracy.E1.angryNeutral_LS_A_top =...
    percent(confusionVectors.E1.angryNeutral_LS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryNeutral_RS_A_top =...
    percent(confusionVectors.E1.angryNeutral_RS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryNeutral_A_top =...
    percent(confusionVectors.E1.angryNeutral_A_top,...
            expression.angry, 2);

% angry top + happy bottom
percentAccuracy.E1.angryHappy_LS_A_top =...
    percent(confusionVectors.E1.angryHappy_LS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryHappy_RS_A_top =...
    percent(confusionVectors.E1.angryHappy_RS_A_top,...
            expression.angry, 2);

percentAccuracy.E1.angryHappy_A_top =...
    percent(confusionVectors.E1.angryHappy_A_top,...
            expression.angry, 2);




% Overall accuracy
%
% happy top + happy bottom
percentAccuracy.E1.overall.happyHappy_LS_A_bottom =...
    mean(percentAccuracy.E1.happyHappy_LS_A_bottom);

percentAccuracy.E1.overall.happyHappy_RS_A_bottom =...
    mean(percentAccuracy.E1.happyHappy_RS_A_bottom);

percentAccuracy.E1.overall.happyHappy_A_bottom =...
    mean(percentAccuracy.E1.happyHappy_A_bottom);

confidenceInterval.percentAccuracy.E1.happyHappy_LS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.happyHappy_LS_A_bottom);

confidenceInterval.percentAccuracy.E1.happyHappy_RS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.happyHappy_RS_A_bottom);

confidenceInterval.percentAccuracy.E1.happyHappy_A_bottom =...
    confidenceinterval(percentAccuracy.E1.happyHappy_A_bottom);


% happy bottom
percentAccuracy.E1.overall.happyBottom_LS =...
    mean(percentAccuracy.E1.happyBottom_LS);

percentAccuracy.E1.overall.happyBottom_RS =...
    mean(percentAccuracy.E1.happyBottom_RS);

percentAccuracy.E1.overall.happyBottom =...
    mean(percentAccuracy.E1.happyBottom);

confidenceInterval.percentAccuracy.E1.happyBottom_LS =...
    confidenceinterval(percentAccuracy.E1.happyBottom_LS);

confidenceInterval.percentAccuracy.E1.happyBottom_RS =...
    confidenceinterval(percentAccuracy.E1.happyBottom_RS);

confidenceInterval.percentAccuracy.E1.happyBottom =...
    confidenceinterval(percentAccuracy.E1.happyBottom);


% neutral top + happy bottom
percentAccuracy.E1.overall.neutralHappy_LS_A_bottom =...
    mean(percentAccuracy.E1.neutralHappy_LS_A_bottom);

percentAccuracy.E1.overall.neutralHappy_RS_A_bottom =...
    mean(percentAccuracy.E1.neutralHappy_RS_A_bottom);

percentAccuracy.E1.overall.neutralHappy_A_bottom =...
    mean(percentAccuracy.E1.neutralHappy_A_bottom);

confidenceInterval.percentAccuracy.E1.neutralHappy_LS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.neutralHappy_LS_A_bottom);

confidenceInterval.percentAccuracy.E1.neutralHappy_RS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.neutralHappy_RS_A_bottom);

confidenceInterval.percentAccuracy.E1.neutralHappy_A_bottom =...
    confidenceinterval(percentAccuracy.E1.neutralHappy_A_bottom);


% angry top + happy bottom
percentAccuracy.E1.overall.angryHappy_LS_A_bottom =...
    mean(percentAccuracy.E1.angryHappy_LS_A_bottom);

percentAccuracy.E1.overall.angryHappy_RS_A_bottom =...
    mean(percentAccuracy.E1.angryHappy_RS_A_bottom);

percentAccuracy.E1.overall.angryHappy_A_bottom =...
    mean(percentAccuracy.E1.angryHappy_A_bottom);

confidenceInterval.percentAccuracy.E1.angryHappy_LS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.angryHappy_LS_A_bottom);

confidenceInterval.percentAccuracy.E1.angryHappy_RS_A_bottom =...
    confidenceinterval(percentAccuracy.E1.angryHappy_RS_A_bottom);

confidenceInterval.percentAccuracy.E1.angryHappy_A_bottom =...
    confidenceinterval(percentAccuracy.E1.angryHappy_A_bottom);




% angry top + angry bottom
percentAccuracy.E1.overall.angryAngry_LS_A_top =...
    mean(percentAccuracy.E1.angryAngry_LS_A_top);

percentAccuracy.E1.overall.angryAngry_RS_A_top =...
    mean(percentAccuracy.E1.angryAngry_RS_A_top);

percentAccuracy.E1.overall.angryAngry_A_top =...
    mean(percentAccuracy.E1.angryAngry_A_top);

confidenceInterval.percentAccuracy.E1.angryAngry_LS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryAngry_LS_A_top);

confidenceInterval.percentAccuracy.E1.angryAngry_RS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryAngry_RS_A_top);

confidenceInterval.percentAccuracy.E1.angryAngry_A_top =...
    confidenceinterval(percentAccuracy.E1.angryAngry_A_top);


% angry top
percentAccuracy.E1.overall.angryTop_LS =...
    mean(percentAccuracy.E1.angryTop_LS);

percentAccuracy.E1.overall.angryTop_RS =...
    mean(percentAccuracy.E1.angryTop_RS);

percentAccuracy.E1.overall.angryTop =...
    mean(percentAccuracy.E1.angryTop);

confidenceInterval.percentAccuracy.E1.angryTop_LS =...
    confidenceinterval(percentAccuracy.E1.angryTop_LS);

confidenceInterval.percentAccuracy.E1.angryTop_RS =...
    confidenceinterval(percentAccuracy.E1.angryTop_RS);

confidenceInterval.percentAccuracy.E1.angryTop =...
    confidenceinterval(percentAccuracy.E1.angryTop);


% angry top + neutral bottom
percentAccuracy.E1.overall.angryNeutral_LS_A_top =...
    mean(percentAccuracy.E1.angryNeutral_LS_A_top);

percentAccuracy.E1.overall.angryNeutral_RS_A_top =...
    mean(percentAccuracy.E1.angryNeutral_RS_A_top);

percentAccuracy.E1.overall.angryNeutral_A_top =...
    mean(percentAccuracy.E1.angryNeutral_A_top);

confidenceInterval.percentAccuracy.E1.angryNeutral_LS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryNeutral_LS_A_top);

confidenceInterval.percentAccuracy.E1.angryNeutral_RS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryNeutral_RS_A_top);

confidenceInterval.percentAccuracy.E1.angryNeutral_A_top =...
    confidenceinterval(percentAccuracy.E1.angryNeutral_A_top);


% angry top + happy bottom
percentAccuracy.E1.overall.angryHappy_LS_A_top =...
    mean(percentAccuracy.E1.angryHappy_LS_A_top);

percentAccuracy.E1.overall.angryHappy_RS_A_top =...
    mean(percentAccuracy.E1.angryHappy_RS_A_top);

percentAccuracy.E1.overall.angryHappy_A_top =...
    mean(percentAccuracy.E1.angryHappy_A_top);

confidenceInterval.percentAccuracy.E1.angryHappy_LS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryHappy_LS_A_top);

confidenceInterval.percentAccuracy.E1.angryHappy_RS_A_top =...
    confidenceinterval(percentAccuracy.E1.angryHappy_RS_A_top);

confidenceInterval.percentAccuracy.E1.angryHappy_A_top =...
    confidenceinterval(percentAccuracy.E1.angryHappy_A_top);




% Reaction Time
%
% Convert confidence to reaction time
reactionTime.experiment1 = 1 - confidence.experiment1;

% happy top + happy bottom
reactionTime.E1.happyHappy_LS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(1,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.happyHappy_LS_A_bottom =...
    meanexclude(reactionTime.E1.happyHappy_LS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.happyHappy_LS_A_bottom =...
    confidenceinterval(reactionTime.E1.happyHappy_LS_A_bottom);


reactionTime.E1.happyHappy_RS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(9,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.happyHappy_RS_A_bottom =...
    meanexclude(reactionTime.E1.happyHappy_RS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.happyHappy_RS_A_bottom =...
    confidenceinterval(reactionTime.E1.happyHappy_RS_A_bottom);


reactionTime.E1.happyHappy_A_bottom =...
    meanexclude([reactionTime.E1.happyHappy_LS_A_bottom,...
                 reactionTime.E1.happyHappy_RS_A_bottom],...
                wrong, 2);
reactionTime.E1.overall.happyHappy_A_bottom =...
    meanexclude(reactionTime.E1.happyHappy_A_bottom, wrong);
confidenceInterval.reactionTime.E1.happyHappy_A_bottom =...
    confidenceinterval(reactionTime.E1.happyHappy_A_bottom);


% happy bottom
reactionTime.E1.happyBottom_LS =...
    meanexclude(reshape(reactionTime.experiment1(2,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.happyBottom_LS =...
    meanexclude(reactionTime.E1.happyBottom_LS, wrong);
confidenceInterval.reactionTime.E1.happyBottom_LS =...
    confidenceinterval(reactionTime.E1.happyBottom_LS);


reactionTime.E1.happyBottom_RS =...
    meanexclude(reshape(reactionTime.experiment1(10,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.happyBottom_RS =...
    meanexclude(reactionTime.E1.happyBottom_RS, wrong);
confidenceInterval.reactionTime.E1.happyBottom_RS =...
    confidenceinterval(reactionTime.E1.happyBottom_RS);


reactionTime.E1.happyBottom =...
    meanexclude([reactionTime.E1.happyBottom_LS,...
                 reactionTime.E1.happyBottom_RS],...
                wrong, 2);
reactionTime.E1.overall.happyBottom =...
    meanexclude(reactionTime.E1.happyBottom, wrong);
confidenceInterval.reactionTime.E1.happyBottom =...
    confidenceinterval(reactionTime.E1.happyBottom);


% neutral top + happy bottom
reactionTime.E1.neutralHappy_LS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(3,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.neutralHappy_LS_A_bottom =...
    meanexclude(reactionTime.E1.neutralHappy_LS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.neutralHappy_LS_A_bottom =...
    confidenceinterval(reactionTime.E1.neutralHappy_LS_A_bottom);


reactionTime.E1.neutralHappy_RS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(11,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.neutralHappy_RS_A_bottom =...
    meanexclude(reactionTime.E1.neutralHappy_RS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.neutralHappy_RS_A_bottom =...
    confidenceinterval(reactionTime.E1.neutralHappy_RS_A_bottom);


reactionTime.E1.neutralHappy_A_bottom =...
    meanexclude([reactionTime.E1.neutralHappy_LS_A_bottom,...
                 reactionTime.E1.neutralHappy_RS_A_bottom],...
                wrong, 2);
reactionTime.E1.overall.neutralHappy_A_bottom =...
    meanexclude(reactionTime.E1.neutralHappy_A_bottom, wrong);
confidenceInterval.reactionTime.E1.neutralHappy_A_bottom =...
    confidenceinterval(reactionTime.E1.neutralHappy_A_bottom);


% angry top + happy bottom
reactionTime.E1.angryHappy_LS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(4,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryHappy_LS_A_bottom =...
    meanexclude(reactionTime.E1.angryHappy_LS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.angryHappy_LS_A_bottom =...
    confidenceinterval(reactionTime.E1.angryHappy_LS_A_bottom);


reactionTime.E1.angryHappy_RS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment1(12,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryHappy_RS_A_bottom =...
    meanexclude(reactionTime.E1.angryHappy_RS_A_bottom, wrong);
confidenceInterval.reactionTime.E1.angryHappy_RS_A_bottom =...
    confidenceinterval(reactionTime.E1.angryHappy_RS_A_bottom);


reactionTime.E1.angryHappy_A_bottom =...
    meanexclude([reactionTime.E1.angryHappy_LS_A_bottom,...
                 reactionTime.E1.angryHappy_RS_A_bottom],...
                wrong, 2);
reactionTime.E1.overall.angryHappy_A_bottom =...
    meanexclude(reactionTime.E1.angryHappy_A_bottom, wrong);
confidenceInterval.reactionTime.E1.angryHappy_A_bottom =...
    confidenceinterval(reactionTime.E1.angryHappy_A_bottom);


% angry top + angry bottom
reactionTime.E1.angryAngry_LS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(5,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryAngry_LS_A_top =...
    meanexclude(reactionTime.E1.angryAngry_LS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryAngry_LS_A_top =...
    confidenceinterval(reactionTime.E1.angryAngry_LS_A_top);


reactionTime.E1.angryAngry_RS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(13,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryAngry_RS_A_top =...
    meanexclude(reactionTime.E1.angryAngry_RS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryAngry_RS_A_top =...
    confidenceinterval(reactionTime.E1.angryAngry_RS_A_top);


reactionTime.E1.angryAngry_A_top =...
    meanexclude([reactionTime.E1.angryAngry_LS_A_top,...
                 reactionTime.E1.angryAngry_RS_A_top],...
                wrong, 2);
reactionTime.E1.overall.angryAngry_A_top =...
    meanexclude(reactionTime.E1.angryAngry_A_top, wrong);
confidenceInterval.reactionTime.E1.angryAngry_A_top =...
    confidenceinterval(reactionTime.E1.angryAngry_A_top);


% angry top
reactionTime.E1.angryTop_LS =...
    meanexclude(reshape(reactionTime.experiment1(6,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryTop_LS =...
    meanexclude(reactionTime.E1.angryTop_LS, wrong);
confidenceInterval.reactionTime.E1.angryTop_LS =...
    confidenceinterval(reactionTime.E1.angryTop_LS);


reactionTime.E1.angryTop_RS =...
    meanexclude(reshape(reactionTime.experiment1(14,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryTop_RS =...
    meanexclude(reactionTime.E1.angryTop_RS, wrong);
confidenceInterval.reactionTime.E1.angryTop_RS =...
    confidenceinterval(reactionTime.E1.angryTop_RS);


reactionTime.E1.angryTop =...
    meanexclude([reactionTime.E1.angryTop_LS,...
                 reactionTime.E1.angryTop_RS],...
                wrong, 2);
reactionTime.E1.overall.angryTop =...
    meanexclude(reactionTime.E1.angryTop, wrong);
confidenceInterval.reactionTime.E1.angryTop =...
    confidenceinterval(reactionTime.E1.angryTop);


% angry top + neutral bottom
reactionTime.E1.angryNeutral_LS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(7,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryNeutral_LS_A_top =...
    meanexclude(reactionTime.E1.angryNeutral_LS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryNeutral_LS_A_top =...
    confidenceinterval(reactionTime.E1.angryNeutral_LS_A_top);


reactionTime.E1.angryNeutral_RS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(15,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryNeutral_RS_A_top =...
    meanexclude(reactionTime.E1.angryNeutral_RS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryNeutral_RS_A_top =...
    confidenceinterval(reactionTime.E1.angryNeutral_RS_A_top);


reactionTime.E1.angryNeutral_A_top =...
    meanexclude([reactionTime.E1.angryNeutral_LS_A_top,...
                 reactionTime.E1.angryNeutral_RS_A_top],...
                wrong, 2);
reactionTime.E1.overall.angryNeutral_A_top =...
    meanexclude(reactionTime.E1.angryNeutral_A_top, wrong);
confidenceInterval.reactionTime.E1.angryNeutral_A_top =...
    confidenceinterval(reactionTime.E1.angryNeutral_A_top);


% angry top + happy bottom
reactionTime.E1.angryHappy_LS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(8,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryHappy_LS_A_top =...
    meanexclude(reactionTime.E1.angryHappy_LS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryHappy_LS_A_top =...
    confidenceinterval(reactionTime.E1.angryHappy_LS_A_top);


reactionTime.E1.angryHappy_RS_A_top =...
    meanexclude(reshape(reactionTime.experiment1(16,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E1.overall.angryHappy_RS_A_top =...
    meanexclude(reactionTime.E1.angryHappy_RS_A_top, wrong);
confidenceInterval.reactionTime.E1.angryHappy_RS_A_top =...
    confidenceinterval(reactionTime.E1.angryHappy_RS_A_top);


reactionTime.E1.angryHappy_A_top =...
    meanexclude([reactionTime.E1.angryHappy_LS_A_top,...
                 reactionTime.E1.angryHappy_RS_A_top],...
                wrong, 2);
reactionTime.E1.overall.angryHappy_A_top =...
    meanexclude(reactionTime.E1.angryHappy_A_top, wrong);
confidenceInterval.reactionTime.E1.angryHappy_A_top =...
    confidenceinterval(reactionTime.E1.angryHappy_A_top);

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION 3 (TANAKA ET AL. EXPERIMENT 3) %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Percent accuracy
%
% happy top + happy bottom
percentAccuracy.E3.happyHappy_LS_A_bottom =...
    percent(confusionVectors.E3.happyHappy_LS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E3.happyHappy_RS_A_bottom =...
    percent(confusionVectors.E3.happyHappy_RS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E3.happyHappy_A_bottom =...
    percent(confusionVectors.E3.happyHappy_A_bottom,...
            expression.happy, 2);


percentAccuracy.E3.happyHappy_TLBR_MA_bottom =...
    percent(confusionVectors.E3.happyHappy_TLBR_MA_bottom,...
            expression.happy, 2);

percentAccuracy.E3.happyHappy_TRBL_MA_bottom =...
    percent(confusionVectors.E3.happyHappy_TRBL_MA_bottom,...
            expression.happy, 2);

percentAccuracy.E3.happyHappy_MA_bottom =...
    percent(confusionVectors.E3.happyHappy_MA_bottom,...
            expression.happy, 2);


% angry top + happy bottom
percentAccuracy.E3.angryHappy_LS_A_bottom =...
    percent(confusionVectors.E3.angryHappy_LS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E3.angryHappy_RS_A_bottom =...
    percent(confusionVectors.E3.angryHappy_RS_A_bottom,...
            expression.happy, 2);

percentAccuracy.E3.angryHappy_A_bottom =...
    percent(confusionVectors.E3.angryHappy_A_bottom,...
            expression.happy, 2);


percentAccuracy.E3.angryHappy_TLBR_MA_bottom =...
    percent(confusionVectors.E3.angryHappy_TLBR_MA_bottom,...
            expression.happy, 2);

percentAccuracy.E3.angryHappy_TRBL_MA_bottom =...
    percent(confusionVectors.E3.angryHappy_TRBL_MA_bottom,...
            expression.happy, 2);

percentAccuracy.E3.angryHappy_MA_bottom =...
    percent(confusionVectors.E3.angryHappy_MA_bottom,...
            expression.happy, 2);


% angry top + angry bottom
percentAccuracy.E3.angryAngry_LS_A_top =...
    percent(confusionVectors.E3.angryAngry_LS_A_top,...
            expression.angry, 2);

percentAccuracy.E3.angryAngry_RS_A_top =...
    percent(confusionVectors.E3.angryAngry_RS_A_top,...
            expression.angry, 2);

percentAccuracy.E3.angryAngry_A_top =...
    percent(confusionVectors.E3.angryAngry_A_top,...
            expression.angry, 2);


percentAccuracy.E3.angryAngry_TLBR_MA_top =...
    percent(confusionVectors.E3.angryAngry_TLBR_MA_top,...
            expression.angry, 2);

percentAccuracy.E3.angryAngry_TRBL_MA_top =...
    percent(confusionVectors.E3.angryAngry_TRBL_MA_top,...
            expression.angry, 2);

percentAccuracy.E3.angryAngry_MA_top =...
    percent(confusionVectors.E3.angryAngry_MA_top,...
            expression.angry, 2);


% angry top + happy bottom
percentAccuracy.E3.angryHappy_LS_A_top =...
    percent(confusionVectors.E3.angryHappy_LS_A_top,...
            expression.angry, 2);

percentAccuracy.E3.angryHappy_RS_A_top =...
    percent(confusionVectors.E3.angryHappy_RS_A_top,...
            expression.angry, 2);

percentAccuracy.E3.angryHappy_A_top =...
    percent(confusionVectors.E3.angryHappy_A_top,...
            expression.angry, 2);


percentAccuracy.E3.angryHappy_TLBR_MA_top =...
    percent(confusionVectors.E3.angryHappy_TLBR_MA_top,...
            expression.angry, 2);

percentAccuracy.E3.angryHappy_TRBL_MA_top =...
    percent(confusionVectors.E3.angryHappy_TRBL_MA_top,...
            expression.angry, 2);

percentAccuracy.E3.angryHappy_MA_top =...
    percent(confusionVectors.E3.angryHappy_MA_top,...
            expression.angry, 2);


% normal
percentAccuracy.E3.normal_A =...
    [percentAccuracy.E3.happyHappy_A_bottom;...
     percentAccuracy.E3.angryAngry_A_top];

percentAccuracy.E3.normal_TLBR_MA =...
    [percentAccuracy.E3.happyHappy_TLBR_MA_bottom;...
     percentAccuracy.E3.angryAngry_TLBR_MA_top];

percentAccuracy.E3.normal_TRBL_MA =...
    [percentAccuracy.E3.happyHappy_TRBL_MA_bottom;...
     percentAccuracy.E3.angryAngry_TRBL_MA_top];

percentAccuracy.E3.normal_MA =...
    [percentAccuracy.E3.happyHappy_MA_bottom;...
     percentAccuracy.E3.angryAngry_MA_top];


% angry-happy
percentAccuracy.E3.angryHappy_A =...
    [percentAccuracy.E3.angryHappy_A_bottom;...
     percentAccuracy.E3.angryHappy_A_top];

percentAccuracy.E3.angryHappy_TLBR_MA =...
    [percentAccuracy.E3.angryHappy_TLBR_MA_bottom;...
     percentAccuracy.E3.angryHappy_TLBR_MA_top];

percentAccuracy.E3.angryHappy_TRBL_MA =...
    [percentAccuracy.E3.angryHappy_TRBL_MA_bottom;...
     percentAccuracy.E3.angryHappy_TRBL_MA_top];

percentAccuracy.E3.angryHappy_MA =...
    [percentAccuracy.E3.angryHappy_MA_bottom;...
     percentAccuracy.E3.angryHappy_MA_top];




% Overall accuracy
%
% happy top + happy bottom
percentAccuracy.E3.overall.happyHappy_LS_A_bottom =...
    mean(percentAccuracy.E3.happyHappy_LS_A_bottom);

percentAccuracy.E3.overall.happyHappy_RS_A_bottom =...
    mean(percentAccuracy.E3.happyHappy_RS_A_bottom);

percentAccuracy.E3.overall.happyHappy_A_bottom =...
    mean(percentAccuracy.E3.happyHappy_A_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_LS_A_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_LS_A_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_RS_A_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_RS_A_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_A_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_A_bottom);


percentAccuracy.E3.overall.happyHappy_TLBR_MA_bottom =...
    mean(percentAccuracy.E3.happyHappy_TLBR_MA_bottom);

percentAccuracy.E3.overall.happyHappy_TRBL_MA_bottom =...
    mean(percentAccuracy.E3.happyHappy_TRBL_MA_bottom);

percentAccuracy.E3.overall.happyHappy_MA_bottom =...
    mean(percentAccuracy.E3.happyHappy_MA_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_TLBR_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_TLBR_MA_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_TRBL_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_TRBL_MA_bottom);

confidenceInterval.percentAccuracy.E3.happyHappy_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.happyHappy_MA_bottom);


% angry top + happy bottom
percentAccuracy.E3.overall.angryHappy_LS_A_bottom =...
    mean(percentAccuracy.E3.angryHappy_LS_A_bottom);

percentAccuracy.E3.overall.angryHappy_RS_A_bottom =...
    mean(percentAccuracy.E3.angryHappy_RS_A_bottom);

percentAccuracy.E3.overall.angryHappy_A_bottom =...
    mean(percentAccuracy.E3.angryHappy_A_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_LS_A_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_LS_A_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_RS_A_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_RS_A_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_A_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_A_bottom);


percentAccuracy.E3.overall.angryHappy_TLBR_MA_bottom =...
    mean(percentAccuracy.E3.angryHappy_TLBR_MA_bottom);

percentAccuracy.E3.overall.angryHappy_TRBL_MA_bottom =...
    mean(percentAccuracy.E3.angryHappy_TRBL_MA_bottom);

percentAccuracy.E3.overall.angryHappy_MA_bottom =...
    mean(percentAccuracy.E3.angryHappy_MA_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_TLBR_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TLBR_MA_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_TRBL_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TRBL_MA_bottom);

confidenceInterval.percentAccuracy.E3.angryHappy_MA_bottom =...
    confidenceinterval(percentAccuracy.E3.angryHappy_MA_bottom);


% angry top + angry bottom
percentAccuracy.E3.overall.angryAngry_LS_A_top =...
    mean(percentAccuracy.E3.angryAngry_LS_A_top);

percentAccuracy.E3.overall.angryAngry_RS_A_top =...
    mean(percentAccuracy.E3.angryAngry_RS_A_top);

percentAccuracy.E3.overall.angryAngry_A_top =...
    mean(percentAccuracy.E3.angryAngry_A_top);

confidenceInterval.percentAccuracy.E3.angryAngry_LS_A_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_LS_A_top);

confidenceInterval.percentAccuracy.E3.angryAngry_RS_A_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_RS_A_top);

confidenceInterval.percentAccuracy.E3.angryAngry_A_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_A_top);


percentAccuracy.E3.overall.angryAngry_TLBR_MA_top =...
    mean(percentAccuracy.E3.angryAngry_TLBR_MA_top);

percentAccuracy.E3.overall.angryAngry_TRBL_MA_top =...
    mean(percentAccuracy.E3.angryAngry_TRBL_MA_top);

percentAccuracy.E3.overall.angryAngry_MA_top =...
    mean(percentAccuracy.E3.angryAngry_MA_top);

confidenceInterval.percentAccuracy.E3.angryAngry_TLBR_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_TLBR_MA_top);

confidenceInterval.percentAccuracy.E3.angryAngry_TRBL_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_TRBL_MA_top);

confidenceInterval.percentAccuracy.E3.angryAngry_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryAngry_MA_top);


% angry top + happy bottom
percentAccuracy.E3.overall.angryHappy_LS_A_top =...
    mean(percentAccuracy.E3.angryHappy_LS_A_top);

percentAccuracy.E3.overall.angryHappy_RS_A_top =...
    mean(percentAccuracy.E3.angryHappy_RS_A_top);

percentAccuracy.E3.overall.angryHappy_A_top =...
    mean(percentAccuracy.E3.angryHappy_A_top);

confidenceInterval.percentAccuracy.E3.angryHappy_LS_A_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_LS_A_top);

confidenceInterval.percentAccuracy.E3.angryHappy_RS_A_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_RS_A_top);

confidenceInterval.percentAccuracy.E3.angryHappy_A_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_A_top);


percentAccuracy.E3.overall.angryHappy_TLBR_MA_top =...
    mean(percentAccuracy.E3.angryHappy_TLBR_MA_top);

percentAccuracy.E3.overall.angryHappy_TRBL_MA_top =...
    mean(percentAccuracy.E3.angryHappy_TRBL_MA_top);

percentAccuracy.E3.overall.angryHappy_MA_top =...
    mean(percentAccuracy.E3.angryHappy_MA_top);

confidenceInterval.percentAccuracy.E3.angryHappy_TLBR_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TLBR_MA_top);

confidenceInterval.percentAccuracy.E3.angryHappy_TRBL_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TRBL_MA_top);

confidenceInterval.percentAccuracy.E3.angryHappy_MA_top =...
    confidenceinterval(percentAccuracy.E3.angryHappy_MA_top);


% normal
percentAccuracy.E3.overall.normal_A =...
    mean(percentAccuracy.E3.normal_A);
percentAccuracy.E3.overall.normal_TLBR_MA =...
    mean(percentAccuracy.E3.normal_TLBR_MA);
percentAccuracy.E3.overall.normal_TRBL_MA =...
    mean(percentAccuracy.E3.normal_TRBL_MA);
percentAccuracy.E3.overall.normal_MA =...
    mean(percentAccuracy.E3.normal_MA);

confidenceInterval.percentAccuracy.E3.normal_A =...
    confidenceinterval(percentAccuracy.E3.normal_A);
confidenceInterval.percentAccuracy.E3.normal_TLBR_MA =...
    confidenceinterval(percentAccuracy.E3.normal_TLBR_MA);
confidenceInterval.percentAccuracy.E3.normal_TRBL_MA =...
    confidenceinterval(percentAccuracy.E3.normal_TRBL_MA);
confidenceInterval.percentAccuracy.E3.normal_MA =...
    confidenceinterval(percentAccuracy.E3.normal_MA);

% angry-happy
percentAccuracy.E3.overall.angryHappy_A =...
    mean(percentAccuracy.E3.angryHappy_A);
percentAccuracy.E3.overall.angryHappy_TLBR_MA =...
    mean(percentAccuracy.E3.angryHappy_TLBR_MA);
percentAccuracy.E3.overall.angryHappy_TRBL_MA =...
    mean(percentAccuracy.E3.angryHappy_TRBL_MA);
percentAccuracy.E3.overall.angryHappy_MA =...
    mean(percentAccuracy.E3.angryHappy_MA);

confidenceInterval.percentAccuracy.E3.angryHappy_A =...
    confidenceinterval(percentAccuracy.E3.angryHappy_A);
confidenceInterval.percentAccuracy.E3.angryHappy_TLBR_MA =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TLBR_MA);
confidenceInterval.percentAccuracy.E3.angryHappy_TRBL_MA =...
    confidenceinterval(percentAccuracy.E3.angryHappy_TRBL_MA);
confidenceInterval.percentAccuracy.E3.angryHappy_MA =...
    confidenceinterval(percentAccuracy.E3.angryHappy_MA);




% Reaction Time
%
% Convert confidence to reaction time
reactionTime.experiment3 = 1 - confidence.experiment3;

% happy top + happy bottom
reactionTime.E3.happyHappy_LS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment3(1,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.happyHappy_LS_A_bottom =...
    meanexclude(reactionTime.E3.happyHappy_LS_A_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_LS_A_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_LS_A_bottom);


reactionTime.E3.happyHappy_RS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment3(2,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.happyHappy_RS_A_bottom =...
    meanexclude(reactionTime.E3.happyHappy_RS_A_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_RS_A_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_RS_A_bottom);


reactionTime.E3.happyHappy_A_bottom =...
    meanexclude([reactionTime.E3.happyHappy_LS_A_bottom,...
                 reactionTime.E3.happyHappy_RS_A_bottom],...
                wrong, 2);
reactionTime.E3.overall.happyHappy_A_bottom =...
    meanexclude(reactionTime.E3.happyHappy_A_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_A_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_A_bottom);




reactionTime.E3.happyHappy_TLBR_MA_bottom =...
    meanexclude(reshape(reactionTime.experiment3(3,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.happyHappy_TLBR_MA_bottom =...
    meanexclude(reactionTime.E3.happyHappy_TLBR_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_TLBR_MA_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_TLBR_MA_bottom);


reactionTime.E3.happyHappy_TRBL_MA_bottom =...
    meanexclude(reshape(reactionTime.experiment3(4,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.happyHappy_TRBL_MA_bottom =...
    meanexclude(reactionTime.E3.happyHappy_TRBL_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_TRBL_MA_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_TRBL_MA_bottom);


reactionTime.E3.happyHappy_MA_bottom =...
    meanexclude([reactionTime.E3.happyHappy_TLBR_MA_bottom,...
                 reactionTime.E3.happyHappy_TRBL_MA_bottom],...
                wrong, 2);
reactionTime.E3.overall.happyHappy_MA_bottom =...
    meanexclude(reactionTime.E3.happyHappy_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.happyHappy_MA_bottom =...
    confidenceinterval(reactionTime.E3.happyHappy_MA_bottom);


% angry top + happy bottom
reactionTime.E3.angryHappy_LS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment3(5,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_LS_A_bottom =...
    meanexclude(reactionTime.E3.angryHappy_LS_A_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_LS_A_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_LS_A_bottom);


reactionTime.E3.angryHappy_RS_A_bottom =...
    meanexclude(reshape(reactionTime.experiment3(6,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_RS_A_bottom =...
    meanexclude(reactionTime.E3.angryHappy_RS_A_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_RS_A_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_RS_A_bottom);


reactionTime.E3.angryHappy_A_bottom =...
    meanexclude([reactionTime.E3.angryHappy_LS_A_bottom,...
                 reactionTime.E3.angryHappy_RS_A_bottom],...
                wrong, 2);
reactionTime.E3.overall.angryHappy_A_bottom =...
    meanexclude(reactionTime.E3.angryHappy_A_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_A_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_A_bottom);




reactionTime.E3.angryHappy_TLBR_MA_bottom =...
    meanexclude(reshape(reactionTime.experiment3(7,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_TLBR_MA_bottom =...
    meanexclude(reactionTime.E3.angryHappy_TLBR_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_TLBR_MA_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_TLBR_MA_bottom);


reactionTime.E3.angryHappy_TRBL_MA_bottom =...
    meanexclude(reshape(reactionTime.experiment3(8,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_TRBL_MA_bottom =...
    meanexclude(reactionTime.E3.angryHappy_TRBL_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_TRBL_MA_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_TRBL_MA_bottom);


reactionTime.E3.angryHappy_MA_bottom =...
    meanexclude([reactionTime.E3.angryHappy_TLBR_MA_bottom,...
                 reactionTime.E3.angryHappy_TRBL_MA_bottom],...
                wrong, 2);
reactionTime.E3.overall.angryHappy_MA_bottom =...
    meanexclude(reactionTime.E3.angryHappy_MA_bottom, wrong);
confidenceInterval.reactionTime.E3.angryHappy_MA_bottom =...
    confidenceinterval(reactionTime.E3.angryHappy_MA_bottom);


% angry top + angry bottom
reactionTime.E3.angryAngry_LS_A_top =...
    meanexclude(reshape(reactionTime.experiment3(9,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryAngry_LS_A_top =...
    meanexclude(reactionTime.E3.angryAngry_LS_A_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_LS_A_top =...
    confidenceinterval(reactionTime.E3.angryAngry_LS_A_top);


reactionTime.E3.angryAngry_RS_A_top =...
    meanexclude(reshape(reactionTime.experiment3(10,:,:),...
                           n.subsets, n.repeats),...
                   wrong, 2);
reactionTime.E3.overall.angryAngry_RS_A_top =...
    meanexclude(reactionTime.E3.angryAngry_RS_A_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_RS_A_top =...
    confidenceinterval(reactionTime.E3.angryAngry_RS_A_top);


reactionTime.E3.angryAngry_A_top =...
    meanexclude([reactionTime.E3.angryAngry_LS_A_top,...
                 reactionTime.E3.angryAngry_RS_A_top],...
                wrong, 2);
reactionTime.E3.overall.angryAngry_A_top =...
    meanexclude(reactionTime.E3.angryAngry_A_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_A_top =...
    confidenceinterval(reactionTime.E3.angryAngry_A_top);




reactionTime.E3.angryAngry_TLBR_MA_top =...
    meanexclude(reshape(reactionTime.experiment3(11,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryAngry_TLBR_MA_top =...
    meanexclude(reactionTime.E3.angryAngry_TLBR_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_TLBR_MA_top =...
    confidenceinterval(reactionTime.E3.angryAngry_TLBR_MA_top);


reactionTime.E3.angryAngry_TRBL_MA_top =...
    meanexclude(reshape(reactionTime.experiment3(12,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryAngry_TRBL_MA_top =...
    meanexclude(reactionTime.E3.angryAngry_TRBL_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_TRBL_MA_top =...
    confidenceinterval(reactionTime.E3.angryAngry_TRBL_MA_top);


reactionTime.E3.angryAngry_MA_top =...
    meanexclude([reactionTime.E3.angryAngry_TLBR_MA_top,...
                 reactionTime.E3.angryAngry_TRBL_MA_top],...
                wrong, 2);
reactionTime.E3.overall.angryAngry_MA_top =...
    meanexclude(reactionTime.E3.angryAngry_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryAngry_MA_top =...
    confidenceinterval(reactionTime.E3.angryAngry_MA_top);


% angry top + happy bottom
reactionTime.E3.angryHappy_LS_A_top =...
    meanexclude(reshape(reactionTime.experiment3(13,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_LS_A_top =...
    meanexclude(reactionTime.E3.angryHappy_LS_A_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_LS_A_top =...
    confidenceinterval(reactionTime.E3.angryHappy_LS_A_top);


reactionTime.E3.angryHappy_RS_A_top =...
    meanexclude(reshape(reactionTime.experiment3(14,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_RS_A_top =...
    meanexclude(reactionTime.E3.angryHappy_RS_A_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_RS_A_top =...
    confidenceinterval(reactionTime.E3.angryHappy_RS_A_top);


reactionTime.E3.angryHappy_A_top =...
    meanexclude([reactionTime.E3.angryHappy_LS_A_top,...
                 reactionTime.E3.angryHappy_RS_A_top],...
                wrong, 2);
reactionTime.E3.overall.angryHappy_A_top =...
    meanexclude(reactionTime.E3.angryHappy_A_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_A_top =...
    confidenceinterval(reactionTime.E3.angryHappy_A_top);




reactionTime.E3.angryHappy_TLBR_MA_top =...
    meanexclude(reshape(reactionTime.experiment3(15,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_TLBR_MA_top =...
    meanexclude(reactionTime.E3.angryHappy_TLBR_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_TLBR_MA_top =...
    confidenceinterval(reactionTime.E3.angryHappy_TLBR_MA_top);

reactionTime.E3.angryHappy_TRBL_MA_top =...
    meanexclude(reshape(reactionTime.experiment3(16,:,:),...
                        n.subsets, n.repeats),...
                wrong, 2);
reactionTime.E3.overall.angryHappy_TRBL_MA_top =...
    meanexclude(reactionTime.E3.angryHappy_TRBL_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_TRBL_MA_top =...
    confidenceinterval(reactionTime.E3.angryHappy_TRBL_MA_top);

reactionTime.E3.angryHappy_MA_top =...
    meanexclude([reactionTime.E3.angryHappy_TLBR_MA_top,...
                 reactionTime.E3.angryHappy_TRBL_MA_top],...
                wrong, 2);
reactionTime.E3.overall.angryHappy_MA_top =...
    meanexclude(reactionTime.E3.angryHappy_MA_top, wrong);
confidenceInterval.reactionTime.E3.angryHappy_MA_top =...
    confidenceinterval(reactionTime.E3.angryHappy_MA_top);


% normal
reactionTime.E3.normal_A =...
    [reactionTime.E3.happyHappy_A_bottom;...
     reactionTime.E3.angryAngry_A_top];
reactionTime.E3.normal_TLBR_MA =...
    [reactionTime.E3.happyHappy_TLBR_MA_bottom;...
     reactionTime.E3.angryAngry_TLBR_MA_top];
reactionTime.E3.normal_TRBL_MA =...
    [reactionTime.E3.happyHappy_TRBL_MA_bottom;...
     reactionTime.E3.angryAngry_TRBL_MA_top];
reactionTime.E3.normal_MA =...
    [reactionTime.E3.happyHappy_MA_bottom;...
     reactionTime.E3.angryAngry_MA_top];

reactionTime.E3.overall.normal_A ...
    = meanexclude(reactionTime.E3.normal_A, wrong);
reactionTime.E3.overall.normal_TLBR_MA ...
    = meanexclude(reactionTime.E3.normal_TLBR_MA, wrong);
reactionTime.E3.overall.normal_TRBL_MA ...
    = meanexclude(reactionTime.E3.normal_TRBL_MA, wrong);
reactionTime.E3.overall.normal_MA ...
    = meanexclude(reactionTime.E3.normal_MA, wrong);

confidenceInterval.reactionTime.E3.normal_A =...
    confidenceinterval(reactionTime.E3.normal_A);
confidenceInterval.reactionTime.E3.normal_TLBR_MA =...
    confidenceinterval(reactionTime.E3.normal_TLBR_MA);
confidenceInterval.reactionTime.E3.normal_TRBL_MA =...
    confidenceinterval(reactionTime.E3.normal_TRBL_MA);
confidenceInterval.reactionTime.E3.normal_MA =...
    confidenceinterval(reactionTime.E3.normal_MA);

% angry-happy
reactionTime.E3.angryHappy_A =...
    [reactionTime.E3.angryHappy_A_bottom;...
     reactionTime.E3.angryHappy_A_top];
reactionTime.E3.angryHappy_TLBR_MA =...
    [reactionTime.E3.angryHappy_TLBR_MA_bottom;...
     reactionTime.E3.angryHappy_TLBR_MA_top];
reactionTime.E3.angryHappy_TRBL_MA =...
    [reactionTime.E3.angryHappy_TRBL_MA_bottom;...
     reactionTime.E3.angryHappy_TRBL_MA_top];
reactionTime.E3.angryHappy_MA =...
    [reactionTime.E3.angryHappy_MA_bottom;...
     reactionTime.E3.angryHappy_MA_top];

reactionTime.E3.overall.angryHappy_A =...
    meanexclude(reactionTime.E3.angryHappy_A, wrong);
reactionTime.E3.overall.angryHappy_TLBR_MA =...
    meanexclude(reactionTime.E3.angryHappy_TLBR_MA, wrong);
reactionTime.E3.overall.angryHappy_TRBL_MA =...
    meanexclude(reactionTime.E3.angryHappy_TRBL_MA, wrong);
reactionTime.E3.overall.angryHappy_MA =...
    meanexclude(reactionTime.E3.angryHappy_MA, wrong);

confidenceInterval.reactionTime.E3.angryHappy_A =...
    confidenceinterval(reactionTime.E3.angryHappy_A);
confidenceInterval.reactionTime.E3.angryHappy_TLBR_MA =...
    confidenceinterval(reactionTime.E3.angryHappy_TLBR_MA);
confidenceInterval.reactionTime.E3.angryHappy_TRBL_MA =...
    confidenceinterval(reactionTime.E3.angryHappy_TRBL_MA);
confidenceInterval.reactionTime.E3.angryHappy_MA =...
    confidenceinterval(reactionTime.E3.angryHappy_MA);