function attendedStimulus =...
    attention4stimulus(partition, attentionMatrix, means)
%ATTENTION4STIMULUS shifts feature values closer to the mean
%   (along each feature dimension) according to how much a
%   feature of a stimulus is NOT attended to. Thereby the
%   contribution of stimulus features to the variance along each
%   dimension is reduced. Since Principal Component Analysis
%   selects the directions of maximal variance in data, features
%   are attenuated accordingly.
%
% INPUT
%   partition           - set of partitions
%   attentionMatrix     - attention matrix
%   means               - row vector of means along each feature
%                         dimension

% OUTPUT
%   attendedStimulus

    attendedStimulus =...
        attention4region(partition.r11,...
                         attentionMatrix(1,1),...
                         means) +...
        attention4region(partition.r12,...
                         attentionMatrix(1,2),...
                         means) +...
        attention4region(partition.r13,...
                         attentionMatrix(1,3),...
                         means) +...
        attention4region(partition.r21,...
                         attentionMatrix(2,1),...
                         means) +...
        attention4region(partition.r22,...
                         attentionMatrix(2,2),...
                         means) +...
        attention4region(partition.r23,...
                         attentionMatrix(2,3),...
                         means);
end